apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: eric-pc-vpn-gw-common
  annotations:
    k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/data_bridge
  labels:
    {{ include "eric-pc-vpn-gw.helm-labels" $ | nindent 4 }}
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "ovs",
    "bridge": "data_bridge",
    "mtu": 1500,
    "trunk": [{ "minID" : 3000, "maxID" : 4000}]
  }'

