######################################
## CNF general information
######################################
nodeName: n47
nodeType: CCES

vnflcm:
  clusterName: n47-eccd1
  namespace: cces
  InstantiateVnfRequest:
    applicationTimeOut: 3600
    skipVerification: "true"

#users:
#  day0:
#    username: sysadmin
#    password: Pa$$w0rd4LDAP

#  day1:
#  - username: ccesoam
#    password: Changeme1st!
#    groups:
#    - nef-admin
#    - apigm-admin
#    - sragent-admin
#    - nrfagent-admin
#    - system-admin
#  - username: ccessec
#    password: Changeme1st!
#    groups:
#    - nef-security-admin
#    - apigm-security-admin
#    - sragent-security-admin
#    - nrfagent-security-admin
#    - system-security-admin

license:
  customerId: "946060"
  swltId: STA-CCES-13

cnom:
  fqdn: cnom.cces1.n47.sero.gic.ericsson.se

#snmp:
#  agentEngineId: 8000137001C0A899ECCD10CEA6

#ddc:
#  remotePath: /lab/pccc_logs/5GC-CICD/ci/N67_DDC/eccd1/n67-cces-ddc

vtap:
  tapagent: true

######################################
## CNF specific information
######################################
cces:
  iamFqdn: iam.cces1.n47.sero.gic.ericsson.se
#  nef:
#    instanceId: ddd9b5b3-fa57-4cb1-ace7-89eccd10cea6
#    host: nef1.n47
#    port: 443
#    nbi:
#      trust:
#        host: nef1-nbi-trust.n47
#    diameter:
#      host: nef1.n47
#      peer:
#        host: pcrf1.epc
#        ip: 25.51.1.251
#        port: 3868

######################################
## CNF dimensioning specific
######################################

replicaCount:
  eric-cces-common-entity: 2
  eric-cces-timer-service: 2
  eric-apigm-api-proxy: 2

hpaReplica:
  eric-cces-common-entity: {min: 2, max: 2}
  eric-cces-timer-service: {min: 2, max: 2}
  eric-apigm-api-proxy: {min: 2, max: 2}
  eric-data-wide-column-database-cd: 5



