apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    meta.helm.sh/release-namespace: ccsm
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: allow-eric-fh-alarm-handler
  namespace: ccsm
  selfLink: /apis/networking.k8s.io/v1/namespaces/ccsm/networkpolicies/allow-eric-fh-alarm-handler
spec:
  egress:
  - {}
  ingress:
  - {}
  podSelector:
    matchLabels:
      app: eric-fh-alarm-handler
  policyTypes:
  - Ingress

