snmp:
  agentEngineId: 8000137001C0A899ECCD10CEA6

license:
  customerId: "946060"
  swltId: STA-CCES-16

nefInstanceId: ddd9b5b3-fa57-4cb1-ace7-99eccd10cea6

ddc:
  remotePath: /home/admin/ddc/eccd3/n84-cces2

diameter:
  remoteIp: 25.51.1.251
  remotePort: 3868

nef:
  host: nef2.n84
  port: 443
nefNbiTrust:
  host: nef2-nbi-trust.n84

