nodeName: ccpc
nodeType: CCPC
instance: 1

vnflcm:
  clusterName: n189-eccd1
  namespace: ccpc
  InstantiateVnfRequest:
    applicationTimeOut: 3600
    skipVerification: "true"

ccpc:
  provFqdn: ccpc1-5g-prov.n189-eccd1.seli.gic.ericsson.se
  pcf:
    instanceId: 98aae42e-da25-4329-acf0-63e2986785aa
    host: ccpc1-5g-traffic.site1-cluster1 
    port: 443
  pcrf:
    diameter:
      host: cpc1-5g-traffic.site1-cluster1

users:
  day0:
    username: sysadmin
    password: Pa$$w0rd4LDAP
  day1:
  - username: ccpcoam
    password: Changeme1st!
    groups:
    - pcf-admin
    - system-admin
    - nrfagent-admin
    - ccpc-prov-admin
  - username: ccpcsec
    password: Changeme1st!
    groups:
    - pcf-security-admin
    - system-security-admin
    - nrfagent-security-admin

certs:
  iccr-external-tls-certificate:
    p12: ../../../../certs/cnf_common_ip/ccpc/ccpc-iccr-server.p12
  eric-ccpc-sbi-server-certificate:
    p12: ../../../../certs/cnf_common_ip/ccpc/ccpc-sbi-server.p12
  eric-ccpc-sbi-client-certificate:
    p12: ../../../../certs/cnf_common_ip/ccpc/ccpc-sbi-client.p12

cnom:
  fqdn: cnom.ccpc1-oam.n189-eccd1.seli.gic.ericsson.se
snmp:
  agentEngineId: 800000c10400000001
  heartbeatInterval: 600
  sourceIdentifier: 10.221.124.74

license:
  customerId: "946060"
  swltId: STA-CCPC-23

ddc:
  remotePath: /lab/pccc_logs/5GC-CICD/ci/N189_DDC/n189-ccpc-ddc

replicaCount:
  eric-pcf-dms: 7
  eric-ccpc-provisioning: 12
  eric-pcf-dms-server: 4

#Remove parameter 'minReplica' and 'maxReplica', using hpaReplica[max, min] to replace
hpaReplica:
  eric-ccpc-data-access:
    max: 15
    min: 9
  eric-pcf-session-management-policy-control:
    max: 6
    min: 4
  eric-pcrf-ipcan-session-management:
    max: 6
    min: 4
  eric-pcf-charging:
    max: 4
    min: 2
  eric-pcf-egress-proxy:
    max: 4
    min: 2
  eric-pcf-ue-policy-control:
    max: 60
    min: 2
  eric-pcf-rx-policy-control:
    max: 10
    min: 2
  eric-pcf-egress-proxy-chf:
    max: 4
    min: 2
  eric-pcf-egress-proxy-bsf:
    max: 4
    min: 2
  eric-pcf-egress-proxy-ccpc:
    max: 30
    min: 2
  eric-pcf-geored-controller:
    max: 1
    min: 1
  eric-pcf-end-user-notifier:
    max: 60
    min: 2
  eric-ccpc-provisioning:
    min: 2
    max: 110
pvcSize:
  eric-pcf-dms-server: 38

