Third-Parties:
  - infra: 'infra://tool-01-201/dp_n/1?type=raw'
    service:
      ltt_drv: 'infra://tool-01-201/ltt/1'
  - infra: 'infra://tool-01-202/dp_n/1?type=raw'
    service:
      ltt_drv: 'infra://tool-01-202/ltt/1'

DPs:
#  - infra: 'infra://tool-01-001/dp_n/1?type=raw'
#    capability:
#      diameter: 'app://dp/local'
#      ess: 'app://dp/local'
#      tcp: 'app://dp/local'
  - infra: 'infra://tool-01-201/dp_n/1?type=raw'
    capability:
      diameter: 'app://dp/local'
      ess: 'app://dp/local'
      http: 'app://dp/local'
      ltt_cp: 'app://third-parties/1'
      ltt_up: 'app://third-parties/1'
      pfcp: 'app://dp/local'
      tcp: 'app://dp/local'

  - infra: 'infra://tool-01-202/dp_n/1?type=raw'
    capability:
      diameter: 'app://dp/local'
      ess: 'app://dp/local'
      http: 'app://dp/local'
      ltt_cp: 'app://third-parties/2'
      ltt_up: 'app://third-parties/2'
      pfcp: 'app://dp/local'
      tcp: 'app://dp/local'

V-DPs:
  - infra: {'infra://tool-01-201/dp_n/1?type=otp', 'infra://tool-01-201/dp_n/1?type=raw'}
  - infra: {'infra://tool-01-202/dp_n/1?type=otp', 'infra://tool-01-202/dp_n/1?type=raw'}

CS:
  infra: 'infra://tool-01-001/ap_n/1?type=otp'

Subsystems:
  - infra: 'infra://tool-01-102/ap_n/1?type=otp'
    vdp: 'app://vdp/1'
    APs:
    - infra: {'infra://tool-01-102/ap_n/2?type=otp', 'infra://tool-01-102/ap_n/2?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/3?type=otp', 'infra://tool-01-102/ap_n/3?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/4?type=otp', 'infra://tool-01-102/ap_n/4?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/5?type=otp', 'infra://tool-01-102/ap_n/5?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/6?type=otp', 'infra://tool-01-102/ap_n/6?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/7?type=otp', 'infra://tool-01-102/ap_n/7?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/8?type=otp', 'infra://tool-01-102/ap_n/8?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/9?type=otp', 'infra://tool-01-102/ap_n/9?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/10?type=otp', 'infra://tool-01-102/ap_n/10?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/11?type=otp', 'infra://tool-01-102/ap_n/11?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/12?type=otp', 'infra://tool-01-102/ap_n/12?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/13?type=otp', 'infra://tool-01-102/ap_n/13?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/14?type=otp', 'infra://tool-01-102/ap_n/14?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/15?type=otp', 'infra://tool-01-102/ap_n/15?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/16?type=otp', 'infra://tool-01-102/ap_n/16?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/17?type=otp', 'infra://tool-01-102/ap_n/17?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/18?type=otp', 'infra://tool-01-102/ap_n/18?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/19?type=otp', 'infra://tool-01-102/ap_n/19?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/20?type=otp', 'infra://tool-01-102/ap_n/20?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/21?type=otp', 'infra://tool-01-102/ap_n/21?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/22?type=otp', 'infra://tool-01-102/ap_n/22?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/23?type=otp', 'infra://tool-01-102/ap_n/23?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/24?type=otp', 'infra://tool-01-102/ap_n/24?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/25?type=otp', 'infra://tool-01-102/ap_n/25?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/26?type=otp', 'infra://tool-01-102/ap_n/26?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/27?type=otp', 'infra://tool-01-102/ap_n/27?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/28?type=otp', 'infra://tool-01-102/ap_n/28?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/29?type=otp', 'infra://tool-01-102/ap_n/29?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/30?type=otp', 'infra://tool-01-102/ap_n/30?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/31?type=otp', 'infra://tool-01-102/ap_n/31?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/32?type=otp', 'infra://tool-01-102/ap_n/32?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/33?type=otp', 'infra://tool-01-102/ap_n/33?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/34?type=otp', 'infra://tool-01-102/ap_n/34?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/35?type=otp', 'infra://tool-01-102/ap_n/35?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/36?type=otp', 'infra://tool-01-102/ap_n/36?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/37?type=otp', 'infra://tool-01-102/ap_n/37?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/38?type=otp', 'infra://tool-01-102/ap_n/38?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/39?type=otp', 'infra://tool-01-102/ap_n/39?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/40?type=otp', 'infra://tool-01-102/ap_n/40?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/41?type=otp', 'infra://tool-01-102/ap_n/41?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/42?type=otp', 'infra://tool-01-102/ap_n/42?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/43?type=otp', 'infra://tool-01-102/ap_n/43?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/44?type=otp', 'infra://tool-01-102/ap_n/44?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/45?type=otp', 'infra://tool-01-102/ap_n/45?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/46?type=otp', 'infra://tool-01-102/ap_n/46?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/47?type=otp', 'infra://tool-01-102/ap_n/47?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/48?type=otp', 'infra://tool-01-102/ap_n/48?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/49?type=otp', 'infra://tool-01-102/ap_n/49?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/50?type=otp', 'infra://tool-01-102/ap_n/50?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/51?type=otp', 'infra://tool-01-102/ap_n/51?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/52?type=otp', 'infra://tool-01-102/ap_n/52?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/53?type=otp', 'infra://tool-01-102/ap_n/53?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/54?type=otp', 'infra://tool-01-102/ap_n/54?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/55?type=otp', 'infra://tool-01-102/ap_n/55?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/56?type=otp', 'infra://tool-01-102/ap_n/56?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/57?type=otp', 'infra://tool-01-102/ap_n/57?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/58?type=otp', 'infra://tool-01-102/ap_n/58?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/59?type=otp', 'infra://tool-01-102/ap_n/59?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/60?type=otp', 'infra://tool-01-102/ap_n/60?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/61?type=otp', 'infra://tool-01-102/ap_n/61?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/62?type=otp', 'infra://tool-01-102/ap_n/62?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/63?type=otp', 'infra://tool-01-102/ap_n/63?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/64?type=otp', 'infra://tool-01-102/ap_n/64?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/65?type=otp', 'infra://tool-01-102/ap_n/65?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/66?type=otp', 'infra://tool-01-102/ap_n/66?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/67?type=otp', 'infra://tool-01-102/ap_n/67?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/68?type=otp', 'infra://tool-01-102/ap_n/68?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/69?type=otp', 'infra://tool-01-102/ap_n/69?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/70?type=otp', 'infra://tool-01-102/ap_n/70?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/71?type=otp', 'infra://tool-01-102/ap_n/71?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/72?type=otp', 'infra://tool-01-102/ap_n/72?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/73?type=otp', 'infra://tool-01-102/ap_n/73?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/74?type=otp', 'infra://tool-01-102/ap_n/74?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/75?type=otp', 'infra://tool-01-102/ap_n/75?type=raw'}
    - infra: {'infra://tool-01-102/ap_n/76?type=otp', 'infra://tool-01-102/ap_n/76?type=raw'}
  - infra: 'infra://tool-01-103/ap_n/1?type=otp'
    vdp: 'app://vdp/2'
    APs:
    - infra: {'infra://tool-01-103/ap_n/2?type=otp', 'infra://tool-01-103/ap_n/2?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/3?type=otp', 'infra://tool-01-103/ap_n/3?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/4?type=otp', 'infra://tool-01-103/ap_n/4?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/5?type=otp', 'infra://tool-01-103/ap_n/5?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/6?type=otp', 'infra://tool-01-103/ap_n/6?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/7?type=otp', 'infra://tool-01-103/ap_n/7?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/8?type=otp', 'infra://tool-01-103/ap_n/8?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/9?type=otp', 'infra://tool-01-103/ap_n/9?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/10?type=otp', 'infra://tool-01-103/ap_n/10?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/11?type=otp', 'infra://tool-01-103/ap_n/11?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/12?type=otp', 'infra://tool-01-103/ap_n/12?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/13?type=otp', 'infra://tool-01-103/ap_n/13?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/14?type=otp', 'infra://tool-01-103/ap_n/14?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/15?type=otp', 'infra://tool-01-103/ap_n/15?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/16?type=otp', 'infra://tool-01-103/ap_n/16?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/17?type=otp', 'infra://tool-01-103/ap_n/17?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/18?type=otp', 'infra://tool-01-103/ap_n/18?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/19?type=otp', 'infra://tool-01-103/ap_n/19?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/20?type=otp', 'infra://tool-01-103/ap_n/20?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/21?type=otp', 'infra://tool-01-103/ap_n/21?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/22?type=otp', 'infra://tool-01-103/ap_n/22?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/23?type=otp', 'infra://tool-01-103/ap_n/23?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/24?type=otp', 'infra://tool-01-103/ap_n/24?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/25?type=otp', 'infra://tool-01-103/ap_n/25?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/26?type=otp', 'infra://tool-01-103/ap_n/26?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/27?type=otp', 'infra://tool-01-103/ap_n/27?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/28?type=otp', 'infra://tool-01-103/ap_n/28?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/29?type=otp', 'infra://tool-01-103/ap_n/29?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/30?type=otp', 'infra://tool-01-103/ap_n/30?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/31?type=otp', 'infra://tool-01-103/ap_n/31?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/32?type=otp', 'infra://tool-01-103/ap_n/32?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/33?type=otp', 'infra://tool-01-103/ap_n/33?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/34?type=otp', 'infra://tool-01-103/ap_n/34?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/35?type=otp', 'infra://tool-01-103/ap_n/35?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/36?type=otp', 'infra://tool-01-103/ap_n/36?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/37?type=otp', 'infra://tool-01-103/ap_n/37?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/38?type=otp', 'infra://tool-01-103/ap_n/38?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/39?type=otp', 'infra://tool-01-103/ap_n/39?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/40?type=otp', 'infra://tool-01-103/ap_n/40?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/41?type=otp', 'infra://tool-01-103/ap_n/41?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/42?type=otp', 'infra://tool-01-103/ap_n/42?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/43?type=otp', 'infra://tool-01-103/ap_n/43?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/44?type=otp', 'infra://tool-01-103/ap_n/44?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/45?type=otp', 'infra://tool-01-103/ap_n/45?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/46?type=otp', 'infra://tool-01-103/ap_n/46?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/47?type=otp', 'infra://tool-01-103/ap_n/47?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/48?type=otp', 'infra://tool-01-103/ap_n/48?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/49?type=otp', 'infra://tool-01-103/ap_n/49?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/50?type=otp', 'infra://tool-01-103/ap_n/50?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/51?type=otp', 'infra://tool-01-103/ap_n/51?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/52?type=otp', 'infra://tool-01-103/ap_n/52?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/53?type=otp', 'infra://tool-01-103/ap_n/53?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/54?type=otp', 'infra://tool-01-103/ap_n/54?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/55?type=otp', 'infra://tool-01-103/ap_n/55?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/56?type=otp', 'infra://tool-01-103/ap_n/56?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/57?type=otp', 'infra://tool-01-103/ap_n/57?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/58?type=otp', 'infra://tool-01-103/ap_n/58?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/59?type=otp', 'infra://tool-01-103/ap_n/59?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/60?type=otp', 'infra://tool-01-103/ap_n/60?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/61?type=otp', 'infra://tool-01-103/ap_n/61?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/62?type=otp', 'infra://tool-01-103/ap_n/62?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/63?type=otp', 'infra://tool-01-103/ap_n/63?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/64?type=otp', 'infra://tool-01-103/ap_n/64?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/65?type=otp', 'infra://tool-01-103/ap_n/65?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/66?type=otp', 'infra://tool-01-103/ap_n/66?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/67?type=otp', 'infra://tool-01-103/ap_n/67?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/68?type=otp', 'infra://tool-01-103/ap_n/68?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/69?type=otp', 'infra://tool-01-103/ap_n/69?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/70?type=otp', 'infra://tool-01-103/ap_n/70?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/71?type=otp', 'infra://tool-01-103/ap_n/71?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/72?type=otp', 'infra://tool-01-103/ap_n/72?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/73?type=otp', 'infra://tool-01-103/ap_n/73?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/74?type=otp', 'infra://tool-01-103/ap_n/74?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/75?type=otp', 'infra://tool-01-103/ap_n/75?type=raw'}
    - infra: {'infra://tool-01-103/ap_n/76?type=otp', 'infra://tool-01-103/ap_n/76?type=raw'}

