global:
  timezone: CET
  applicationId: eric-n84-pcg003
  ericsson:
    licensing:
      licenseDomains:
        - productType: 'PACKET_CORE_GATEWAY'
          customerId: '946060'
          swltId: 'STA-SC-3'


eric-pc-kvdb-rd-server:
  numberOfMaster: 6

eric-cm-yang-provider:
  service:
    annotations:
      addressPoolName: pcg-oam
      sharedVIPLabel: pcg-oam

eric-data-search-engine:
  replicaCount:
     data: 3
  persistence: 
    data: 
      persistentVolumeClaim: 
        size: 50Gi
  resources:
    master:
      requests:
        cpu: 0
        memory: 0
    ingest:
      requests:
        cpu: 0
        memory: 0
    data:
      requests:
        cpu: 0
        memory: 0


snmp-alarm-provider-secret-creation:
  enabled: false
eric-fh-snmp-alarm-provider:
  service:
    annotations:
     addressPoolName: pcg-oam
     sharedVIPLabel: pcg-oam
    secretName: snmp-alarm-provider-config
  oamVIP:
    enabled: false

eric-odca-diagnostic-data-collector:
  resources:
    diagnostic-data-collector:
      limits:
        memory: 0
        cpu: 0
        ephemeral-storage: 30Gi
      requests:
        memory: 0
        cpu: 0
        ephemeral-storage: 24Gi

eric-pc-routing-engine:
  interfaces:
    type: macvlan
    macvlan:
      - master: eth4

eric-pc-up-data-plane:
  replicaCount: 1
  acceleratedIo:
    enabled: true
    driver: bifurcated
  applications:
  - name: app100
  nodeSelector:
    type: high-throughput
  resources:
    dataPlane:
      limits:
        cpu: "14"
        hugepages-1Gi: 1Gi
        memory: 18Gi
        intel.com/dp_sriov_mlx5_left: "1"
        intel.com/dp_sriov_mlx5_right: "1"
      requests:
        cpu: "14"
        hugepages-1Gi: 1Gi
        memory: 18Gi
        intel.com/dp_sriov_mlx5_left: "1"
        intel.com/dp_sriov_mlx5_right: "1"
  interfaces:
    - name: net1
      type: host-device
      resourceName: 'intel.com/dp_sriov_mlx5_left'
    - name: net2
      type: host-device
      resourceName: 'intel.com/dp_sriov_mlx5_right'

  tolerations:
  - effect: NoSchedule
    key: high-throughput
    operator: Equal
    value: "true"

eric-pc-up-pfcp-endpoint:
  resources:
    pfcpEndpoint:
      requests:
        cpu: 400m
        memory: 8Gi
      limits:
        cpu: '1'
        memory: 8Gi
  
  replicaCount: 6
  podDisruptionBudget:
    minAvailable: 75%
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 30
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 30

eric-data-coordinator-zk:
  resources:
    datacoordinatorzk:
      requests:
        cpu: 0
        memory: 0
    jmxExporter:
      requests:
        cpu: 0
        memory: 0
eric-data-message-bus-kf:
  resources:
    messagebuskf:
      requests:
        cpu: 0
        memory: 0
    jmxExporter:
      requests:
        cpu: 0
        memory: 0
eric-fh-alarm-handler:
  replicaCount: 1
  resources:
    alarmhandler:
      requests:
        memory: 0
        cpu: 0
eric-pm-bulk-reporter:
  resources:
    bulkreporter:
      requests:
        cpu: 0
        memory: 0
    alarmreporter:
      requests:
        cpu: 0
        memory: 0
    pmsftp:
      requests:
        cpu: 0
        memory: 0
eric-pm-server:
  rbac:
    appMonitoring:
      configFileCreate: false
      enabled: true
  server:
    persistentVolume:
      enabled: true
      size: 64Gi
  resources:
    server:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
    configmapReload:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
    pmExporter:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
    reverseProxy:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
eric-log-shipper:
  resources:
    logshipper:
      requests:
        memory: 0
        cpu: 0
eric-dst-query:
  resources:
    cassandra:
      requests:
        memory: 0
        cpu: 0
    elasticsearch:
      requests:
        memory: 0
        cpu: 0
eric-dst-agent:
  resources:
    requests:
      memory: 0
      cpu: 0
eric-dst-collector:
  resources:
    cassandra:
      requests:
        memory: 0
        cpu: 0
    elasticsearch:
      requests:
        memory: 0
        cpu: 0
eric-sec-sip-tls:
  resources:
    sip:
      requests:
        memory: 0
        cpu: 0
eric-sec-access-mgmt:
  resources:
    iam:
      requests:
        memory: 0
        cpu: 0
eric-sec-key-management:
  resources:
    vault:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
    unsealer:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
    ca:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
    shelter:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
eric-tm-external-connectivity-frontend:
  images:
    controller:
      resources:
        requests:
          cpu: 0
          memory: 0
    speaker:
      resources:
        requests:
          cpu: 0
          memory: 0
eric-data-document-database-pg-cm:
  resources:
    postgres:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
    metrics:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
    kube_client:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
    base_os:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
    brm:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
    bra:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
eric-data-document-database-pg-fh:
  resources:
    postgres:
      requests:
        memory: 0
        cpu: 0
    metrics:
      requests:
        memory: 0
        cpu: 0
    kube_client:
      requests:
        memory: 0
        cpu: 0
    base_os:
      requests:
        memory: 0
        cpu: 0
eric-data-document-database-pg-sec:
  resources:
    postgres:
      requests:
        memory: 0
        cpu: 0
    metrics:
      requests:
        memory: 0
        cpu: 0
    kube_client:
      requests:
        memory: 0
        cpu: 0
    base_os:
      requests:
        memory: 0
        cpu: 0
eric-data-document-database-pg-iam:
  resources:
    postgres:
      requests:
        memory: 0
        cpu: 0
    metrics:
      requests:
        memory: 0
        cpu: 0
    kube_client:
      requests:
        memory: 0
        cpu: 0
    base_os:
      requests:
        memory: 0
        cpu: 0
eric-data-document-database-pg-ah:
  resources:
    postgres:
      requests:
        memory: 0
        cpu: 0
    metrics:
      requests:
        memory: 0
        cpu: 0
    kube_client:
      requests:
        memory: 0
        cpu: 0
    base_os:
      requests:
        memory: 0
        cpu: 0
eric-pc-rs-controller:
  resources:
    requests:
      cpu: 0
      memory: 0
eric-cnom-document-database-mg:
  resources:
    eric-cnom-document-database-mg:
      requests:
        cpu: 0
        memory: 0
eric-data-document-database-pg:
  resources:
    postgres:
      requests:
        memory: 0
        cpu: 0
    metrics:
      requests:
        memory: 0
        cpu: 0
    kube_client:
      requests:
        memory: 0
        cpu: 0
    base_os:
      requests:
        memory: 0
        cpu: 0
eric-data-distributed-coordinator-ed:
  resources:
    etcd:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
    brAgent:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
    webserver:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
eric-pc-mm-gtp-forwarder:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  replicaCount: 1

eric-sec-certm:
  resources:
    certm:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'

eric-sec-admin-user-management:
  resources:
    aum:
      requests:
        cpu: '0'
        memory: '0'
      limits:
        cpu: '0'
        memory: '0'

eric-pc-up-user-plane-cm-agent:
  replicaCount: 1
  resources:
    requests:
      memory: '0'
      cpu: '0'
    limits:
      memory: '0'
      cpu: '0'
eric-data-object-storage-mn:
  server:
    resources:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
  mgt:
    resources:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
  affinity:
    podAntiAffinity: "soft"
eric-data-search-engine-curator:
  resources:
    curator:
      requests:
        memory: '0'
        cpu: '0'
      limits:
        memory: '0'
        cpu: '0'
eric-pc-up-timer-wheel:
  replicaCount: 1
  resources:
    requests:
      memory: '0'
      cpu: '0'
    limits:
      memory: '0'
      cpu: '0'


eric-cnom-server:
  service:
    type: LoadBalancer
  annotations:
    metallb.universe.tf/address-pool: pcg-oam
    metallb.universe.tf/allow-shared-ip: pcg-oam

eric-data-sftp-server:
  service:
    annotations:
      sharedVIPLabel: "pcg-oam"
      addressPoolName: "pcg-oam"

eric-sec-ldap-server:
  adminCredentials:
    adminuser: day0
    adminpasswd: "$6$TM/5VKWKuB3dCjfr$DK89VUXTx6AaEt5XyOrcb3jdOzf3KoZ9gDHgm6XPNUV.kLdzj2bhfyK/7ttu0mxSfAYvSw2gIOWBmrTo6RMQu1"
  resources:
    ldap:
      requests:
        cpu: '0'
        memory: '0'
      limits:
        cpu: '0'
        memory: '0'
    ldapagent:
      requests:
        cpu: '0'
        memory: '0'
      limits:
        cpu: '0'
        memory: '0'

eric-pc-up-partitioner:
  resources:
    partitioner:
      requests:
        cpu: 200m
        memory: 40Mi
        ephemeral-storage:
      limits:
        cpu: '1'
        memory: 8Gi
        ephemeral-storage:


eric-log-transformer:
  jvmHeap: 4000m
  replicaCount: 2
  resources:
    requests:
      cpu: 0
      memory: 0
    logtransformer:
      requests:
        cpu: 0
        memory: 0
eric-cm-mediator:
  resources:
    eric-cm-mediator:
      limits:
        memory: 1024Mi
eric-pc-up-br-agent:
  resources:
    brAgent:
      limits:
        memory: 512Mi

eric-pc-networking-cm-agent:
  replicaCount: 1

eric-pc-routing-aggregator:
  replicaCount: 1

eric-pc-routing-engine-api:
  replicaCount: 1


eric-lm-combined-server:
  licenseServerClient:
    licenseServer:
      thrift:
        host: 10.221.14.88
        port: 9095
