#EVNFM version 23.1.0
global:
  createClusterRoles: true
  hosts:
    gas: 'gas01.eoaas.n47.vpod1.sc.sero.gic.ericsson.se'
    gr: ''
    iam: 'iam01.eoaas.n47.vpod1.sc.sero.gic.ericsson.se'
    vnfm: 'evnfm01.eoaas.n47.vpod1.sc.sero.gic.ericsson.se'
  ingressClass: oss_iccr
  registry:
    password: 'ReGstR@N47vp1'
    url: 'n47-vpod1-registry.sc.sero.gic.ericsson.se'
    username: 'admin'
  serviceMesh:
    enabled: false
  meshConfig:
    enableTracing: false
    defaultConfig:
      tracing:
        sampling: 10
  proxy:
    tracer: zipkin
  tracer:
    zipkin:
      address: ''
  support:
    ipv6:
      enabled: false
  timezone: CET
  ericsson:
#    licensing:
#      licenseDomains:
#      - productType: ''
#        swltId: ''
#        customerId: ''
#      nelsConfiguration:
#        primary:
#          hostname: ''
    licensing:
      licenseDomains:
      - customerId: "946060"
        productType: Ericsson_Orchestrator
        swltId: STA-EVNFM-15
      nelsConfiguration:
        primary:
          hostname: nelsaas-vnf1-thrift.sero.gic.ericsson.se

tags:
  eoCm: false
  eoEvnfm: true
  eoVmvnfm: true
eric-cloud-native-base:
  eric-ctrl-bro:
    persistence:
      persistentVolumeClaim:
        size: 300Gi
  eric-data-search-engine:
    service:
      network:
        protocol:
          IPv6: false
  eric-sec-access-mgmt:
    accountManager:
      enabled: false
      inactivityThreshold: 9999
    replicaCount: 2
  eric-tm-ingress-controller-cr:
    enabled: true
    service:
      loadBalancerIP: '214.13.224.135'
      annotations:
        cloudProviderLB: {}
      externalTrafficPolicy: Local
  eric-log-transformer:
    egress:
      syslog:
        enabled: false
        tls:
          enabled: true
        remoteHosts: []
  eric-data-object-storage-mn:
    persistentVolumeClaim:
      size: 10Gi
  eric-fh-snmp-alarm-provider:
    sendAlarm: false
  eric-lm-combined-server:
    licenseServerClient:
      licenseServer:
        thrift:
          host: 'nelsaas-vnf1-thrift.sero.gic.ericsson.se'
geo-redundancy:
  enabled: false
eric-oss-common-base:
  service-mesh-ingress-gateway:
    service:
      loadBalancerIP: ''
  sessionTokens:
    maxSessionDurationSecs: 36000
    maxIdleTimeSecs: 1800
  eric-gr-bur-orchestrator:
    credentials:
      username: ''
      password: ''
    gr:
      bro:
        autoDelete:
          backupsLimit: 10
      sftp:
        url: ''
        username: ''
        password: ''
      cluster:
        role: ''
        secondary_hostnames:
        - ''
      registry:
        secondarySiteContainerRegistryHostname: ''
  system-user:
    credentials:
      username: 'system-username'
      password: 'DefaultP123456!'
  gas:
    defaultUser:
      username: 'gas-user'
      password: 'DefaultP12345!'
  eric-eo-usermgmt:
    replicaCount: 2
  eric-eo-usermgmt-ui:
    replicaCount: 2
eric-oss-function-orchestration-common:
  eric-am-onboarding-service:
    resources:
      limits:
        memory: 32Gi
    userSecret: container-credentials
  eric-eo-evnfm-nbi:
    eric-evnfm-rbac:
      defaultUser:
        username: 'vnfm-user'
        password: 'DefaultP12345!'
eric-eo-evnfm:
  services:
    onboarding:
      enabled: true
#  eric-am-common-wfs:
#    helm:
#      url: ''
#    dockerRegistry:
#      secret: null
  eric-am-common-wfs:
    userSecret: container-credentials
  eric-lcm-container-registry:
    enabled: true
    highAvailability: false
    ingress:
      hostname: 'registry01.eoaas.n47.vpod1.sc.sero.gic.ericsson.se'
    persistence:
      persistentVolumeClaim:
        size: 450Gi
  eric-global-lcm-container-registry:
    hostname: ''
    username: ''
    password: ''
  eric-lcm-helm-chart-registry:
    ingress:
      enabled: true
      hostname: 'helm01.eoaas.n47.vpod1.sc.sero.gic.ericsson.se'
    env:
      secret:
        BASIC_AUTH_USER: 'test'
        BASIC_AUTH_PASS: 'Test@1234'
  eric-vnfm-orchestrator-service:
    oss:
      topology:
        secretName: null
    smallstack:
      application: true
eric-eo-evnfm-vm:
  eric-vnflcm-service:
    oss:
      secretName: null
    persistentVolumeClaim:
      size: 20Gi
    service:
      enabled: false
      loadBalancerIP: '::'
      externalTrafficPolicy: Local
