nodeName: n189
nodeType: SC
instance: 1
vnflcm:
  clusterName: n189-eccd1
  namespace: sc
  InstantiateVnfRequest:
    applicationTimeOut: 3600
    skipVerification: "true"

users:
  day0:
    username: admin
    password: rootroot
  day1:
  - username: tsadm
    password: tsadm
    groups: [ system-admin system-security-admin sc-admin bsf-admin bsf-security-admin scp-admin scp-security-admin sc-security-admin sc-read-only ]

cnom:
  fqdn: cnom.sc1-oam.n189-eccd1.seli.gic.ericsson.se


license:
  customerId: '946060'
  swltId: STA-SC-9
snmp:
  agentEngineId: 800000c10400000007
  heartbeatInterval: 600
  sourceIdentifier: 10.221.124.86
ddc:
  remotePath: /lab/pccc_logs/5GC-CICD/ci/N189_DDC/n189-sc-ddc
vtap:
 remotePath: vtap
sc:
 bsf:
   instanceId: 652e666f-88f9-4864-914f-627366a1c1d1
   host: sc1-bsf-sig.site1-cluster1
   ip: 172.17.128.18
   diameter:
     ip: 172.17.128.17
 scp:
   enabled: false
 sepp:
   enabled: false

######################################
## CNF certificates
######################################
certs:
  iccr-external-tls-certificate:
    p12: ../../../../certs/cnf_common_ip/sc/sc-iccr-server.p12
  eric-bsf-sbi-server-certs:
    p12: ../../../../certs/cnf_common_ip/sc/sc-bsf-sbi-server.p12
  eric-bsf-sbi-client-certs:
    p12: ../../../../certs/cnf_common_ip/sc/sc-bsf-sbi-client.p12
#  eric-scp-sbi-server-certs:
#    p12: ../../../../certs/cnf_common_ip/sc/sc-scp-sbi-server.p12
#  eric-scp-sbi-client-certs:
#    p12: ../../../../certs/cnf_common_ip/sc/sc-scp-sbi-client.p12
