global:
  createClusterRoles: true
  hosts:
    gas: oss.evnfm1.n189-eccd1.seli.gic.ericsson.se
    gr: ''
    iam: iam.evnfm1.n189-eccd1.seli.gic.ericsson.se
    pf: ''
    so: ''
    uds: ''
    vnfm: eo-nbi.evnfm1.n189-eccd1.seli.gic.ericsson.se
  registry:
    password: 'admin123'
    url: 'container-registry.ingress.n189-eccd1.seli.gic.ericsson.se'
    username: 'admin'
  serviceMesh:
    enabled: true
  meshConfig:
    enableTracing: false
    defaultConfig:
      tracing:
        sampling: 10
  proxy:
    tracer: zipkin
  tracer:
    zipkin:
      address: ''
  support:
    ipv6:
      enabled: false
  timezone: CET
  ericsson:
    licensing:
      licenseDomains:
      - customerId: 946060
        applicationId: 946060_STA-EVNFM-29_Ericsson_Orchestrator
        productType: Ericsson_Orchestrator
        swltId: STA-EVNFM-29
      nelsConfiguration:
        primary:
          hostname: nelsaas-vnf1-thrift.sero.gic.ericsson.se
          ip: 10.155.142.68
tags:
  eoCm: false
  eoEvnfm: true
  eoVmvnfm: false
eric-cloud-native-base:
  eric-ctrl-bro:
    persistence:
      persistentVolumeClaim:
        size: 20Gi
  eric-data-search-engine:
    service:
      network:
        protocol:
          IPv6: false
  eric-sec-access-mgmt:
    accountManager:
      enabled: false
      inactivityThreshold: 9999
    replicaCount: 2
    logLevel: debug
  eric-tm-ingress-controller-cr:
    enabled: false
    service:
      loadBalancerIP: 214.6.199.135
      annotations:
        cloudProviderLB: {}
      externalTrafficPolicy: Cluster
    resources:
      envoy:
        limits:
          memory: 500Mi
      contour:
        limits:
          cpu: "2.2"
          memory: 4Gi
  eric-log-transformer:
    egress:
      syslog:
        enabled: false
        tls:
          enabled: true
        remoteHosts: []
  eric-data-object-storage-mn:
    persistentVolumeClaim:
      size: 10Gi
  eric-fh-snmp-alarm-provider:
    sendAlarm: false
  eric-lm-combined-server:
    licenseServerClient:
      licenseServer:
        thrift:
          host: nelsaas-vnf1-thrift.sero.gic.ericsson.se
          port: 9095
geo-redundancy:
  enabled: false
eric-oss-common-base:
  service-mesh-ingress-gateway:
    service:
      loadBalancerIP: 214.6.199.135
      annotations:
        cloudProviderLB: {}
  sessionTokens:
    maxSessionDurationSecs: 36000
    maxIdleTimeSecs: 1800
  eric-gr-bur-orchestrator:
    credentials:
      username: ''
      password: ''
    gr:
      bro:
        autoDelete:
          backupsLimit: 10
      sftp:
        url: ''
        username: ''
        password: ''
      cluster:
        role: ''
        secondary_hostnames:
        - ''
      registry:
        secondarySiteContainerRegistryHostname: ''
  system-user:
    credentials:
      username: system-username
      password: DefaultP123456!
  gas:
    defaultUser:
      username: gas-user
      password: DefaultP12345!
  eric-eo-usermgmt:
    replicaCount: 2
  eric-eo-usermgmt-ui:
    replicaCount: 2
eric-oss-function-orchestration-common:
  eric-eo-evnfm-nbi:
    eric-evnfm-rbac:
      defaultUser:
        username: 'vnfm-user'
        password: 'DefaultP12345!'
  eric-am-onboarding-service:
    container:
      registry:
        enabled: true
    userSecret: container-credentials
eric-eo-evnfm:
  services:
    onboarding:
      enabled: true
  eric-am-common-wfs:
    userSecret: container-credentials
    helm:
      url: ''
    dockerRegistry:
      secret: null
  eric-lcm-container-registry:
    enabled: true
    highAvailability: true
    ingress:
      hostname: 'docker-registry.evnfm1.n189-eccd1.seli.gic.ericsson.se'
    persistence:
      persistentVolumeClaim:
        size: 450Gi
  eric-global-lcm-container-registry:
    hostname: ''
    username: ''
    password: ''
  eric-lcm-helm-chart-registry:
    ingress:
      enabled: false
      hostname: ''
    env:
      secret:
        BASIC_AUTH_USER: ''
        BASIC_AUTH_PASS: ''
  eric-vnfm-orchestrator-service:
    oss:
      topology:
        secretName: null
    smallstack:
      application: true
eric-eo-evnfm-vm:
  eric-vnflcm-service:
    oss:
      secretName: null
    persistentVolumeClaim:
      size: 20Gi
    service:
      enabled: false
      loadBalancerIP: '::'
      externalTrafficPolicy: Local
