######################################
## CNF general information
######################################
nodeName: node299-cluster1-ccpc1
nodeType: CCPC
instance: 1

vnflcm:
  clusterName: node299-cluster1
  namespace: ccpc1
  InstantiateVnfRequest:
    applicationTimeOut: 3600
    skipVerification: "true"

users:
#  day0:
#    username: sysadmin
#    password: Dm5GC@S0lut!on
  day1:
  - username: ccpc-admin
    password: Changeme@1st
    groups:
    - pcf-admin
    - sragent-admin
    - system-admin
    - nrfagent-admin
    - pcf-prov-admin
  - username: ccpc-sec
    password: Changeme@1st
    groups:
    - pcf-security-admin
    - system-security-admin
    - nrfagent-security-admin

license:
  customerId: "946060"
  swltId: STA-CCPC-15  #DM5GC-NODE299-C1-CCPC1-1    #STA-CCPC-15

cnom:
  fqdn: cnom.ccpc1-oam.node299-cluster1.sero.gic.ericsson.se

snmp:
  agentEngineId: 800000c104636370633163317331
  sourceIdentifier: 10.221.124.11

ddc:
  remotePath: /root/ddc/node299-cluster1-ccpc1

#vtap:
#  tapagent: false

######################################
## CNF certificates specific
######################################
certs:
  iccr-external-tls-certificate:
    p12: ../../../../certs/cnf/ccpc/ccpc1-iccr-server.p12
  eric-ccpc-sbi-server-certificate:
    p12: ../../../../certs/cnf/ccpc/ccpc1-sbi-server.p12
  eric-ccpc-sbi-client-certificate:
    p12: ../../../../certs/cnf/ccpc/ccpc1-sbi-client.p12

######################################
## CNF specific information
######################################
ccpc:
  provFqdn: ccpc1-5g-prov.node299-cluster1.sero.gic.ericsson.se
  smfSbiNotifyHost: pcc1-smf-notification.site1-cluster1
  pcf:
    instanceId: 98aae42e-da25-4329-acf0-504346a1c1d1
    host: ccpc1-5g-traffic.site1-cluster1
    port: 443
  pcrf:
    diameter:
      host: node299-cluster1-ccpc1-pcrf
#      port: 3868

replicaCount:
  eric-pcf-dms-server: 3
  eric-stm-diameter: 2

hpaReplica:
  eric-pcf-session-management-policy-control: {min: 2, max: 4}
  eric-ccpc-data-access: {min: 2, max: 4}
  eric-pcf-egress-proxy: {min: 2, max: 4}
  eric-pcrf-ipcan-session-management: {min: 2, max: 4}
  eric-pcf-egress-proxy-ccpc: {min: 2, max: 10}
  eric-pcf-rx-policy-control: {min: 2, max: 4}
  eric-pcf-egress-proxy-bsf: {min: 2, max: 2}
  eric-pcf-end-user-notifier: {min: 2, max: 4}
  eric-pcf-ue-policy-control: {min: 2, max: 2}
  eric-pcf-charging: {min: 2, max: 2}
  eric-pcf-egress-proxy-chf: {min: 2, max: 2}
  eric-mesh-controller: {min: 2, max: 4}
  eric-ccpc-provisioning: {min: 2, max: 12}
