nodeName: n89-pcc
nodeType: PCC
vnflcm:
  clusterName: n89
  namespace: pcc
  InstantiateVnfRequest:
    applicationTimeOut: 1800
    skipVerification: "true"
users:
  day0:
    username: day0
    password: day0
  day1:
  - username: tsadm
    password: tsadm
    groups: [ system-admin system-security-admin mm-config-admin mm-lawful-intercept-admin mm-gsh-lawful-intercept-admin mm-itc-admin mm-security-admin mm-admin mm-read-only-operator mm-expert-admin sm-admin sm-cdr-admin sm-charging-admin sm-itc-admin sm-lawful-intercept-admin sm-operator sm-tracing-admin sm-uetrace-admin system-troubleshooter system-read-only admin ]
 
license:
  customerId: '946060'
  swltId: STA-PCC-9
snmp:
  agentEngineId: 8000137001C0A8720BBDC2842D
  heartbeatInterval: 600
hss:
- ip: 107.2.0.8
replicaCount:
  eric-pc-mm-forwarder: 8  # mandatory, as PC-MM networking configurations reply on this number.
  eric-pc-mm-mobility: 16
  eric-pc-sm-sgw-session: 5
  eric-pc-sm-smf-pgw-session: 8
  eric-pc-sm-nsmf-forwarder: 6
  eric-pc-kvdb-rd-server: 13
  eric-pc-mm-sctp: 7
  eric-pc-vpn-gateway-forwarder: 2

ddc:
  remotePath: /lab/pccc_logs/5GC-CICD/ci/N89_DDC/n89-pcc
pcc:
  dns:
    server: pccc-tool-niv-n89-01
    ipv4: 11.100.2.51
  ipRule:
    defaultGws: [1]
    bfdPeers: [2,3]
    fwdIpFrom: 11
    bgpNeighbors: [2,3]
    creIpFrom: 11
    vpngwIpFrom: 15
  pcmm:
    enabled: true
    nodeId: amf1-n89
    mmeGroupId: 32768
    mmeCode: 13
    amfRegionId: 255
    amfSetId: 2
    amfPointer: 13
    amfCapacity: 50
    amfInstanceId: 8b85f3f9-2f66-4698-b07e-63a07010632e
    namfLbIp: 107.2.0.7
    pgwups5s8NI: media_cn
    ipNetwork: # Only support IPv4
    - name: MEDIA_CN
      ipInt:
        vlan: 100
        ipv4: 11.106.1.0/27
      ipSvc:
      - name: S10-GTP-C
        ipv4: 106.1.0.33
      - name: S11-GTP-C
        ipv4: 106.1.0.65
    - name: SIG_CN_1
      ipInt:
        vlan: 101
        ipv4: 11.106.2.0/27
      ipSvc:
      - name: S6a-1
        ipv4: 106.2.0.65
    - name: SIG_CN_2
      ipInt:
        vlan: 128
        ipv4: 11.106.2.32/27
      ipSvc:
      - name: S6a-2
        ipv4: 106.2.0.97
    - name: RAN_1
      ipInt:
        vlan: 102
        ipv4: 11.106.4.0/27
      ipSvc:
      - name: S1-MME-1
        ipv4: 106.4.0.65
      - name: N2-1
        ipv4: 106.4.0.129
    - name: RAN_2
      ipInt:
        vlan: 130
        ipv4: 11.106.4.32/27
      ipSvc:
      - name: S1-MME-2
        ipv4: 106.4.0.97
      - name: N2-2
        ipv4: 106.4.0.161
    - name: OM_CN
      ipInt:
        vlan: 136
        ipv4: 11.106.3.0/27
      ipSvc:
      - name: OAM
        ipv4: 10.221.124.79
      - name: NTP
        ipv4: 10.221.124.79
  pcsm:
    smfInstanceId: d67766fc-210f-4ecf-858f-cc42a60fc00e
    nsmfLbIp: 107.2.0.1
    nsmfNotifLbIp: 107.2.0.2
    nsmfLogicalIntLbNI: sig_cn
    sgwuPfcpAddress: 108.2.0.33
    sgwups5s8NI: media_cn
    internetPool:
      ipv4: 16.0.0.0/9
      ipv6: 2a01:1::/44
    imsPool:
      ipv4: 16.128.0.0/9
      ipv6: 2a01:1:10::/44
    smfSbiNotifyHost: smf1-notif.n89
    smfSbiNsmfHost: smf1.n89.smf
    pcrfDiameterAddress: 107.2.0.14
    smLogicalInt:
      pgwS5s8c:
        ipv4: 107.2.2.225
        networkInstance: sig_cn
      gomc:
        ipv4: 107.2.1.193
        networkInstance: sig_cn
      sxb:
        ipv4: 107.2.1.161
        networkInstance: sig_cn
      s4s11c:
        ipv4: 107.1.0.1
        networkInstance: media_cn
      sgwS5s8c:
        ipv4: 107.2.2.193
        networkInstance: sig_cn
      sxa:
        ipv4: 107.2.1.97
        networkInstance: sig_cn
      dns:
        ipv4: 10.63.71.239
        networkInstance: om_cn
  vpngw:
    maxNum: 8
    loopback:
      ipv4: 109.2.0.1
      networkInstance: sig_cn
    intraForward:
      vlan: 3400
      ipv4: 172.16.3.0/24
    networkInstances:
    - name: sig_cn
      localAs: 10922
      remoteAs: 102
      ipForward:
        vlan: 161
        ipv4: 11.109.2.0/24
      vnfLoop:
        ipv4: 109.2.1.254
    - name: media_cn
      localAs: 10912
      remoteAs: 101
      ipForward:
        vlan: 160
        ipv4: 11.109.1.0/24
      vnfLoop:
        ipv4: 109.1.1.254
ntpServer:
  ip1: 10.221.17.6
  ip2: 10.221.17.46
DiagnosticDC:
  remoteAddress: 11.100.3.51
  remotePort: 22
  remotePath: /lab/pccc_logs/5GC-CICD/ci/N89_DDC/n89-pcc-ddc
  clientIdentityUser: root
  clientIdentityPwd: bG1jX3hkZwo=
interfaceType: ovs
pcc_pcmm_nw_extra: true
pcmm_nw_extra:
  ipNetwork:
  - name: lb_sig_cn
    ipSvc:
    - name: SBI-Server
      ipv4: 107.2.0.7
    - name: SBI-Client
      ipv4: 106.2.2.1