pre_install:
    - name: disable_puppet_due_to_PCGW-4936
      executable: "/usr/bin/puppet agent"
      arg: "--disable 'Disable puppet Dallas 1 installed - PCGW-4936'"
      host: [ pccc-node299-dallas-01, pccc-node299-dallas-02, pccc-node299-misc-01, pccc-node299-misc-02 ]

    - name: bind_dpdk
      executable: "/root/dallas_sw/dallas_cxp9033923_3r209b02/3pp/ltt/dpdk/lts_bind_dpdk --dpdk_dir /local/dallas/3pp/RHEL-7.9/dpdk/21.11-6"
      arg: "/var/dallas/tap.conf"
      host: [ pccc-node299-dallas-01, pccc-node299-dallas-02 ]
      debug: on

post_install:
    - name: add routes for host
      executable: "/bin/bash /root/script/configure_ip_address_on_tap.sh"
      arg: ""
      host: [ pccc-node299-dallas-01, pccc-node299-dallas-02 ]
      debug: on

post_uninstall:
    - name: unbind_dpdk
      executable: "/root/dallas_sw/dallas_cxp9033923_3r209b02/3pp/ltt/dpdk/lts_unbind_dpdk --dpdk_dir /local/dallas/3pp/RHEL-7.9/dpdk/21.11-6"
      host: [ pccc-node299-dallas-01, pccc-node299-dallas-02 ]
