Third-Parties:
  - infra: 'infra://pccc-tool-niv-249-07/dp_n/1?type=raw'
    service:
      ltt_drv: 'infra://pccc-tool-niv-249-07/ltt/1'
  - infra: 'infra://pccc-tool-niv-249-08/dp_n/1?type=raw'
    service:
      ltt_drv: 'infra://pccc-tool-niv-249-08/ltt/1'
  - infra: 'infra://pccc-tool-niv-249-09/dp_n/1?type=raw'
    service:
      ltt_drv: 'infra://pccc-tool-niv-249-09/ltt/1'
  - infra: 'infra://pccc-tool-niv-249-10/dp_n/1?type=raw'
    service:
      ltt_drv: 'infra://pccc-tool-niv-249-10/ltt/1'
  - infra: 'infra://pccc-tool-niv-249-11/dp_n/1?type=raw'
    service:
      ltt_drv: 'infra://pccc-tool-niv-249-11/ltt/1'
  - infra: 'infra://pccc-tool-niv-249-12/dp_n/1?type=raw'
    service:
      ltt_drv: 'infra://pccc-tool-niv-249-12/ltt/1'

DPs:
  - infra: 'infra://pccc-tool-niv-249-07/dp_n/1?type=raw'
    capability:
      diameter: 'app://dp/local'
      ess: 'app://dp/local'
      http: 'app://dp/local'
      ltt_cp: 'app://third-parties/1'
      ltt_up: 'app://third-parties/1'
      pfcp: 'app://dp/local'
      tcp: 'app://dp/local'
  - infra: 'infra://pccc-tool-niv-249-08/dp_n/1?type=raw'
    capability:
      diameter: 'app://dp/local'
      ess: 'app://dp/local'
      http: 'app://dp/local'
      ltt_cp: 'app://third-parties/2'
      ltt_up: 'app://third-parties/2'
      pfcp: 'app://dp/local'
      tcp: 'app://dp/local'
  - infra: 'infra://pccc-tool-niv-249-09/dp_n/1?type=raw'
    capability:
      diameter: 'app://dp/local'
      ess: 'app://dp/local'
      http: 'app://dp/local'
      ltt_cp: 'app://third-parties/3'
      ltt_up: 'app://third-parties/3'
      pfcp: 'app://dp/local'
      tcp: 'app://dp/local'
  - infra: 'infra://pccc-tool-niv-249-10/dp_n/1?type=raw'
    capability:
      diameter: 'app://dp/local'
      ess: 'app://dp/local'
      http: 'app://dp/local'
      ltt_cp: 'app://third-parties/4'
      ltt_up: 'app://third-parties/4'
      pfcp: 'app://dp/local'
      tcp: 'app://dp/local'
  - infra: 'infra://pccc-tool-niv-249-11/dp_n/1?type=raw'
    capability:
      diameter: 'app://dp/local'
      ess: 'app://dp/local'
      http: 'app://dp/local'
      ltt_cp: 'app://third-parties/5'
      ltt_up: 'app://third-parties/5'
      pfcp: 'app://dp/local'
      tcp: 'app://dp/local'
  - infra: 'infra://pccc-tool-niv-249-12/dp_n/1?type=raw'
    capability:
      diameter: 'app://dp/local'
      ess: 'app://dp/local'
      http: 'app://dp/local'
      ltt_cp: 'app://third-parties/6'
      ltt_up: 'app://third-parties/6'
      pfcp: 'app://dp/local'
      tcp: 'app://dp/local'

V-DPs:
  - infra: {'infra://pccc-tool-niv-249-07/dp_n/1?type=otp', 'infra://pccc-tool-niv-249-07/dp_n/1?type=raw'}
  - infra: {'infra://pccc-tool-niv-249-08/dp_n/1?type=otp', 'infra://pccc-tool-niv-249-08/dp_n/1?type=raw'}
  - infra: {'infra://pccc-tool-niv-249-09/dp_n/1?type=otp', 'infra://pccc-tool-niv-249-09/dp_n/1?type=raw'}
  - infra: {'infra://pccc-tool-niv-249-10/dp_n/1?type=otp', 'infra://pccc-tool-niv-249-10/dp_n/1?type=raw'}
  - infra: {'infra://pccc-tool-niv-249-11/dp_n/1?type=otp', 'infra://pccc-tool-niv-249-11/dp_n/1?type=raw'}
  - infra: {'infra://pccc-tool-niv-249-12/dp_n/1?type=otp', 'infra://pccc-tool-niv-249-12/dp_n/1?type=raw'}

CS:
  infra: 'infra://pccc-tool-niv-249-07/ap_n/1?type=otp'

Subsystems:
  - infra: 'infra://pccc-tool-niv-249-07/ap_n/2?type=otp'
    vdp: 'app://vdp/1'
    APs:
    - infra: {'infra://pccc-tool-niv-249-07/ap_n/3?type=otp', 'infra://pccc-tool-niv-249-07/ap_n/3?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-07/ap_n/4?type=otp', 'infra://pccc-tool-niv-249-07/ap_n/4?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-07/ap_n/5?type=otp', 'infra://pccc-tool-niv-249-07/ap_n/5?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-07/ap_n/6?type=otp', 'infra://pccc-tool-niv-249-07/ap_n/6?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-07/ap_n/7?type=otp', 'infra://pccc-tool-niv-249-07/ap_n/7?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-07/ap_n/8?type=otp', 'infra://pccc-tool-niv-249-07/ap_n/8?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-07/ap_n/9?type=otp', 'infra://pccc-tool-niv-249-07/ap_n/9?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-07/ap_n/10?type=otp', 'infra://pccc-tool-niv-249-07/ap_n/10?type=raw'}
  - infra: 'infra://pccc-tool-niv-249-08/ap_n/1?type=otp'
    vdp: 'app://vdp/2'
    APs:
    - infra: {'infra://pccc-tool-niv-249-08/ap_n/2?type=otp', 'infra://pccc-tool-niv-249-08/ap_n/2?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-08/ap_n/3?type=otp', 'infra://pccc-tool-niv-249-08/ap_n/3?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-08/ap_n/4?type=otp', 'infra://pccc-tool-niv-249-08/ap_n/4?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-08/ap_n/5?type=otp', 'infra://pccc-tool-niv-249-08/ap_n/5?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-08/ap_n/6?type=otp', 'infra://pccc-tool-niv-249-08/ap_n/6?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-08/ap_n/7?type=otp', 'infra://pccc-tool-niv-249-08/ap_n/7?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-08/ap_n/8?type=otp', 'infra://pccc-tool-niv-249-08/ap_n/8?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-08/ap_n/9?type=otp', 'infra://pccc-tool-niv-249-08/ap_n/9?type=raw'}
  - infra: 'infra://pccc-tool-niv-249-09/ap_n/1?type=otp'
    vdp: 'app://vdp/3'
    APs:
    - infra: {'infra://pccc-tool-niv-249-09/ap_n/2?type=otp', 'infra://pccc-tool-niv-249-09/ap_n/2?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-09/ap_n/3?type=otp', 'infra://pccc-tool-niv-249-09/ap_n/3?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-09/ap_n/4?type=otp', 'infra://pccc-tool-niv-249-09/ap_n/4?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-09/ap_n/5?type=otp', 'infra://pccc-tool-niv-249-09/ap_n/5?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-09/ap_n/6?type=otp', 'infra://pccc-tool-niv-249-09/ap_n/6?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-09/ap_n/7?type=otp', 'infra://pccc-tool-niv-249-09/ap_n/7?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-09/ap_n/8?type=otp', 'infra://pccc-tool-niv-249-09/ap_n/8?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-09/ap_n/9?type=otp', 'infra://pccc-tool-niv-249-09/ap_n/9?type=raw'}
  - infra: 'infra://pccc-tool-niv-249-10/ap_n/1?type=otp'
    vdp: 'app://vdp/4'
    APs:
    - infra: {'infra://pccc-tool-niv-249-10/ap_n/2?type=otp', 'infra://pccc-tool-niv-249-10/ap_n/2?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-10/ap_n/3?type=otp', 'infra://pccc-tool-niv-249-10/ap_n/3?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-10/ap_n/4?type=otp', 'infra://pccc-tool-niv-249-10/ap_n/4?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-10/ap_n/5?type=otp', 'infra://pccc-tool-niv-249-10/ap_n/5?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-10/ap_n/6?type=otp', 'infra://pccc-tool-niv-249-10/ap_n/6?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-10/ap_n/7?type=otp', 'infra://pccc-tool-niv-249-10/ap_n/7?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-10/ap_n/8?type=otp', 'infra://pccc-tool-niv-249-10/ap_n/8?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-10/ap_n/9?type=otp', 'infra://pccc-tool-niv-249-10/ap_n/9?type=raw'}
  - infra: 'infra://pccc-tool-niv-249-11/ap_n/1?type=otp'
    vdp: 'app://vdp/5'
    APs:
    - infra: {'infra://pccc-tool-niv-249-11/ap_n/2?type=otp', 'infra://pccc-tool-niv-249-11/ap_n/2?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-11/ap_n/3?type=otp', 'infra://pccc-tool-niv-249-11/ap_n/3?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-11/ap_n/4?type=otp', 'infra://pccc-tool-niv-249-11/ap_n/4?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-11/ap_n/5?type=otp', 'infra://pccc-tool-niv-249-11/ap_n/5?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-11/ap_n/6?type=otp', 'infra://pccc-tool-niv-249-11/ap_n/6?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-11/ap_n/7?type=otp', 'infra://pccc-tool-niv-249-11/ap_n/7?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-11/ap_n/8?type=otp', 'infra://pccc-tool-niv-249-11/ap_n/8?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-11/ap_n/9?type=otp', 'infra://pccc-tool-niv-249-11/ap_n/9?type=raw'}
  - infra: 'infra://pccc-tool-niv-249-12/ap_n/1?type=otp'
    vdp: 'app://vdp/6'
    APs:
    - infra: {'infra://pccc-tool-niv-249-12/ap_n/2?type=otp', 'infra://pccc-tool-niv-249-12/ap_n/2?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-12/ap_n/3?type=otp', 'infra://pccc-tool-niv-249-12/ap_n/3?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-12/ap_n/4?type=otp', 'infra://pccc-tool-niv-249-12/ap_n/4?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-12/ap_n/5?type=otp', 'infra://pccc-tool-niv-249-12/ap_n/5?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-12/ap_n/6?type=otp', 'infra://pccc-tool-niv-249-12/ap_n/6?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-12/ap_n/7?type=otp', 'infra://pccc-tool-niv-249-12/ap_n/7?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-12/ap_n/8?type=otp', 'infra://pccc-tool-niv-249-12/ap_n/8?type=raw'}
    - infra: {'infra://pccc-tool-niv-249-12/ap_n/9?type=otp', 'infra://pccc-tool-niv-249-12/ap_n/9?type=raw'}

