pre_install:
    - name: disable_puppet_due_to_PCGW-4936
      executable: "/usr/bin/puppet agent"
      arg: "--disable 'Disable puppet Dallas 1 installed - PCGW-4936'"
      host: [ pccc-node182-dallas-01 ]

    - name: bind_dpdk
      executable: "/root/dallas_sw/3R183B02/3pp/ltt/dpdk/lts_bind_dpdk -d /local/dallas/3pp/RHEL-7.9/dpdk/18.11-2/share/dpdk"
      arg: "/var/dallas/tap.conf"
      host: [ pccc-node182-dallas-01 ]
      debug: on

post_install:
    - name: add routes for host pccc-node182-dallas-01
      executable: "/bin/bash /root/script/add_nonltt_route.sh"
      arg: "-c 1 -i 2 -a 214.13.238.0/24:10.221.124.64/27"
      host: [ pccc-node182-dallas-01 ]
      debug: on


post_uninstall:
    - name: unbind_dpdk
      executable: "/root/dallas_sw/3R183B02/3pp/ltt/dpdk/lts_unbind_dpdk -d /local/dallas/3pp/RHEL-7.9/dpdk/18.11-2/share/dpdk"
      host: [ pccc-node182-dallas-01 ]