nodeName: n182-pcg1
nodeType: PCG
vnflcm:
  clusterName: n182
  namespace: pcg
  InstantiateVnfRequest:
    applicationTimeOut: 1200
    skipVerification: "true"

users:
  day0:
    username: sysadmin
    password: sysadmin
  day1:
  - username: tsadm
    password: tsadm
    groups: [ system-admin system-troubleshooter ]

ddc:
  remotePath: /lab/pccc_logs/5GC-CICD/ci/N182_DDC/n182-pcg-ddc

license:
  customerId: '946060'
  swltId: STA-PCG-20
snmp:
#not found agentEngineId in old files, give a fake agentEngineId
  agentEngineId: 800000c10400000099
  heartbeatInterval: 600
replicaCount:
  eric-pc-up-data-plane: 24
  eric-pc-kvdb-rd-server: 7
  eric-pc-up-pfcp-endpoint: 8

pcg:
  routingEngine:
    predefine: false
  nicVendor: mellanox
  dpMaxNum: 28
  dpCpu: 12
  nicResrName:
  - mellanox.com/mlnx_left
  - mellanox.com/mlnx_right
  ipRule:
    ipv4:
      defaultGw: [1]
      bgpNeighbors: [2,3]
      creIpFrom: 21
      dpIpFrom: 31
    ipv6:
      defaultGw: [1]
      bgpNeighbors: [2,3]
      creIpFrom: 21
      dpIpFrom: 31
  intraForward:
    vlan: 2210
    ipv4: 172.21.128.0/24
  networkInstances:
  - name: sig_cn
    vrf: sig_cn
    localAs: 4202111002
    remoteAs: 4251100002
    ipForward:
      vlan: 2202
      ipv4: 172.22.32.0/24
    vnfLoop:
      ipv4: 172.18.32.254
    upLoop:
    - name: cp
      ipv4: 172.18.32.1
      interfaces:
      - type: cp-function
        name: sxn4u
      - type: pfcp
        name: sxn4
  - name: toext_open1
    localAs: 4202111005
    remoteAs: 4251100005
    ipForward:
      vlan: 2205
      ipv4: 172.22.128.0/24
      ipv6: fdac:22:128::/64
    dpLoop:
      ipv4: 172.18.128.0/25
      ipv6: fdac:18:128::/64
    vnfLoop:
      ipv4: 172.18.128.254
      ipv6: fdac:18:128::fe
    ipPools:
    - 21.0.0.0/11
    - 21.64.0.0/11
    - fd21:1::/44
    - fd21:1:200::/44
  - name: ran
    localAs: 4202111004
    remoteAs: 4251100004
    ipForward:
      vlan: 2204
      ipv4: 172.22.64.0/24
    dpLoop:
      ipv4: 172.18.192.0/25
    vnfLoop:
      ipv4: 172.18.192.254
    upLoop:
    - name: ran_access
      ipv4: 172.18.64.0/25
      interfaces:
      - type: access
        name: s1n3


  - name: media_cn
    localAs: 4202111001
    remoteAs: 4251100001
    ipForward:
      vlan: 2201
      ipv4: 172.22.0.0/24
    dpLoop:
      ipv4: 172.18.96.0/25
      ipv4addr: 172.18.96.1
    vnfLoop:
      ipv4: 172.18.96.254
    upLoop:
    - name: media_cn_pgw
      ipv4: 172.18.0.0/25
      interfaces:
      - type: access
        name: s5s8u
        default: false
    - name: media_cn_sgw
      ipv4: 172.18.0.128/25
      interfaces:
      - type: core
        name: s5s8u
