######################################
## CNF general information
######################################
systemProfile: small
nodeName: node299-cluster1-ccsm1
nodeType: CCSM
instance: 1
nodeSelector: {}

vnflcm:
  clusterName: node299-cluster1
  namespace: ccsm1

users:
  day1:
  - username: ccsm-admin
    password: Changeme@1st
    groups:
    - ausf_admin
    - udm_sensitive_key_admin
    - udm_admin
    - system-admin
    - nrfagent-admin
    - hssepc_admin
    - ccsm-admin
    - eir_admin
    - hssims_admin # Used for voice
  - username: ccsm-sec
    password: Changeme@1st
    groups:
    - udm_security_admin
    - nrfagent-security-admin
    - system-security-admin

license:
  customerId: '946060'
  swltId: STA-CCSM-44  #DM5GC-NODE299-C1-CCSM1-1    #STA-CCSM-44

cnom:
  fqdn: cnom.ccsm1-oam.node299-cluster1.sero.gic.ericsson.se

snmp:
  agentEngineId: 800000c1046363736d3163317331
  sourceIdentifier: 10.221.124.14

ddc:
  remotePath: /root/ddc/node299-cluster1-ccsm1

#vtap:
#  tapagent: false

######################################
## CNF specific information
######################################
ccsm:
  ausf:
    instanceId: 0c765084-9cc5-49c6-9876-415553a1c1d1
    host: ccsm1-ausf-5g-sig.site1-cluster1
    port: 443
  udm:
    instanceId: 841d1b7c-5103-11e9-8c09-55444da1c1d1
    host: ccsm1-udm-5g-sig.site1-cluster1
    port: 443
#  eir:
#    instanceId:
#    host:
#    port:
  hss:
    instanceId: 9448c0d3-6590-4e54-b90f-485353a1c1d1
    host: ccsm1-hss-epc-http-sig.site1-cluster1
    port: 443
    diameter:
      host: esm

  ims:
    as:
      - id: cx.malt.n299.5gc.mnc081.mcc240.3gppnetwork.org
        name: sip:cx@ims.mnc081.mcc240.3gppnetwork.org
        realm: 5gc.mnc081.mcc240.3gppnetwork.org
      - id: ims.mnc081.mcc240.3gppnetwork.org
        name: sip:application@ims.mnc081.mcc240.3gppnetwork.org
        realm: ims.mnc081.mcc240.3gppnetwork.org
      - id: ericsson.se
        name: sip:cx@ericsson.se
        realm: ericsson.se
    sh:
      - host: ccsm1-hss-epc-http-sig.site1-cluster1.5gc.mnc081.mcc240.3gppnetwork.org
        realm: 5gc.mnc081.mcc240.3gppnetwork.org
    cx:
      - host: esm.ericsson.se
        realm: ericsson.se
    serviceType:
      - id: profile1
        defaultApplicationServer: test
        defaultAsHandling: session_continued
      - id: mtas
        defaultApplicationServer: test
        defaultAsHandling: session_continued
      - id: mtasunreg
        defaultApplicationServer: test
        defaultAsHandling: session_terminated

######################################
## CNF certificates specific
######################################
certs:
  iccr-external-tls-certificate:
    p12: ../../../../certs/cnf/ccsm/ccsm1-iccr-server.p12
#  eric-ccsm-sbi-server-certs:
#    p12: ../../certificates/ccsm1/ccsm1-sbi-server.p12
#  eric-ccsm-sbi-client-certs:
#    p12: ../../certificates/ccsm1/ccsm1-sbi-client.p12
  eric-ccsm-udm-sbi-server-certs:
    p12: ../../../../certs/cnf/ccsm/ccsm1-udm-sbi-server.p12
  eric-ccsm-udm-sbi-client-certs:
    p12: ../../../../certs/cnf/ccsm/ccsm1-udm-sbi-client.p12
  eric-ccsm-ausf-sbi-server-certs:
    p12: ../../../../certs/cnf/ccsm/ccsm1-ausf-sbi-server.p12
  eric-ccsm-ausf-sbi-client-certs:
    p12: ../../../../certs/cnf/ccsm/ccsm1-ausf-sbi-client.p12
  eric-ccsm-hss-sbi-server-certs:
    p12: ../../../../certs/cnf/ccsm/ccsm1-hss-sbi-server.p12
  eric-ccsm-hss-sbi-client-certs:
    p12: ../../../../certs/cnf/ccsm/ccsm1-hss-sbi-client.p12
  eric-ccsm-eir-sbi-server-certs:
    p12: ../../../../certs/cnf/ccsm/ccsm1-eir-sbi-server.p12
  eric-ccsm-eir-sbi-client-certs:
    p12: ../../../../certs/cnf/ccsm/ccsm1-eir-sbi-client.p12

######################################
## CNF dimensioning specific
######################################
hpaReplica:
  eric-ausf-capacity: {min: 1, max: 20}
  eric-ausf-engine: {min: 2, max: 2}
  eric-ccsm-smsengine: {min: 2, max: 2}
  eric-udm-amfeenotifications: {min: 2, max: 2}
  eric-udm-amfeesubscriptions: {min: 2, max: 2}
  eric-udm-autoprovisioning: {min: 2, max: 2}
  eric-udm-blackhole: {min: 1, max: 2}
  eric-udm-cancelepclocation: {min: 2, max: 2}
  eric-udm-capacity: {min: 1, max: 20}
  eric-udm-eapauth: {min: 2, max: 2}
  eric-udm-eapprimeauth: {min: 2, max: 2}
  eric-udm-epsauth: {min: 2, max: 2}
  eric-udm-gbaauth: {min: 2, max: 2}
  eric-udm-imsauth: {min: 2, max: 2}
  eric-udm-iratamfdereg: {min: 2, max: 3}
  eric-udm-iratamflocation: {min: 2, max: 2}
  eric-udm-iratamfdereg: {min: 2, max: 2}
  eric-udm-iratsndereg: {min: 2, max: 2}
  eric-udm-iwk5g2g: {min: 2, max: 2}
  eric-udm-mtsmsdeliverystatus: {min: 2, max: 2}
  eric-udm-mtsmsreadystatus: {min: 2, max: 2}
  eric-udm-mtsmsroutinginfo: {min: 2, max: 2}
  eric-udm-mtsmswaitingdata: {min: 2, max: 2}
  eric-udm-mtueinfo: {min: 2, max: 2}
  eric-udm-mtlocation: {min: 2, max: 2}
  eric-udm-pcscfrestnotif: {min: 2, max: 10}
  eric-udm-pcscfrestoration: {min: 2, max: 2}
  eric-udm-sdmamdata: {min: 2, max: 2}
  eric-udm-sdmimplicitunsub: {min: 2, max: 2}
  eric-udm-sdmmultipledataset: {min: 2, max: 2}
  eric-udm-sdmnotif: {min: 2, max: 2}
  eric-udm-sdmnssai: {min: 2, max: 2}
  eric-udm-sdmsmdata: {min: 2, max: 2}
  eric-udm-sdmsmfselect: {min: 2, max: 2}
  eric-udm-sdmsmsdata: {min: 2, max: 2}
  eric-udm-sdmsmsmngdata: {min: 2, max: 2}
  eric-udm-sdmsubscriptions: {min: 2, max: 2}
  eric-udm-sdmuectxtsmf: {min: 2, max: 2}
  eric-udm-sdmuectxtsmsf: {min: 2, max: 2}
  eric-udm-sidf: {min: 1, max: 1}
  eric-udm-ueauth: {min: 2, max: 2}
  eric-udm-uecmamfderegnotifier: {min: 1, max: 1}
  eric-udm-uecmamfget: {min: 2, max: 2}
  eric-udm-uecmamfderegnotifier: {min: 3, max: 3}
  eric-udm-uecmamfregupdate: {min: 2, max: 2}
  eric-udm-uecmreg: {min: 2, max: 2}
  eric-udm-uecmsmfderegistration: {min: 2, max: 2}
  eric-udm-uecmsmfregistration: {min: 2, max: 2}
  eric-udm-uecmsmsfdereg: {min: 2, max: 2}
  eric-udm-uecmsmsfregget: {min: 2, max: 2}
  eric-udm-uecmsmsfregistration: {min: 2, max: 2}
  eric-udm-ueshcm: {min: 2, max: 2}
  eric-udm-umtsauth: {min: 2, max: 2}
  eric-udm-eesubscribe: {min: 2, max: 2}
  eric-udm-eeunsubscribe: {min: 2, max: 2}
  eric-udm-eesubsidchangenotif: {min: 2, max: 2}
  eric-eir-capacity: {min: 1, max: 1}
  eric-eir-diametereireic: {min: 2, max: 2}
  eric-eir-eireic: {min: 2, max: 2}
  eric-eir-httpnotifier: {min: 2, max: 2}
  eric-eir-infocollector: {min: 2, max: 2}
  eric-eir-infocollectorunsucc: {min: 1, max: 2}
  eric-eir-mapeireic: {min: 2, max: 2}
  eric-eir-s13diameter: {min: 2, max: 2}
  eric-eir-diametereireic: {min: 2, max: 2}
  eric-hssepc-capacity: {min: 1, max: 20}
  eric-hssepc-mttadsinfo: {min: 2, max: 2}
  eric-hssepc-mtuesrvcccap: {min: 2, max: 2}
  eric-hssepc-mtstnsrget: {min: 2, max: 2}
  eric-hssepc-mtstnsrput: {min: 2, max: 2}
  eric-hssepc-mtlocation: {min: 2, max: 2}
  eric-hssepc-pcscfrestoration: {min: 2, max: 10}
  eric-hssepc-iratsndereg: {min: 2, max: 2}
  eric-hssepc-s6aauthentication: {min: 2, max: 2}
  eric-hssepc-s6acancellocation: {min: 2, max: 2}
  eric-hssepc-s6adeletesubscriber: {min: 2, max: 2}
  eric-hssepc-s6adiameter: {min: 2, max: 2}
  eric-hssepc-iratsndereg: {min: 4, max: 5}
  eric-hssepc-s6aauthentication: {min: 5, max: 6}
  eric-hssepc-s6acancellocation: {min: 4, max: 5}
  eric-hssepc-s6adeletesubscriber: {min: 2, max: 2}
  eric-hssepc-s6ainsertsubscriber: {min: 2, max: 2}
  eric-hssepc-s6anotify: {min: 2, max: 2}
  eric-hssepc-s6apurge: {min: 2, max: 2}
  eric-hssepc-s6aupdatelocation: {min: 2, max: 2}
  eric-hssepc-soap: {min: 2, max: 2}
  eric-hssepc-subscriptionupdate: {min: 2, max: 2}
  eric-hssepc-swxdiameter: {min: 2, max: 2}
  eric-hssepc-swxsarreg: {min: 2, max: 2}
  eric-hssepc-swxsardereg: {min: 2, max: 2}
  eric-hssepc-swxsarpgw: {min: 2, max: 2}
  eric-hssepc-swxmar: {min: 2, max: 2}
  eric-hssepc-swxsdmunsub: {min: 2, max: 2}
  eric-hssims-shudrrepodata: {min: 2, max: 2}
  eric-hssims-shudrimsi: {min: 2, max: 2}
  eric-hssims-shudrimspublicidentity: {min: 2, max: 2}
  eric-hssims-shudrimsuserstate: {min: 2, max: 2}
  eric-hssims-shudrcharginginformation: {min: 2, max: 2}
  eric-hssims-shudrscscfname: {min: 2, max: 2}
  eric-hssims-shudrmsisdns: {min: 2, max: 2}
  eric-hssims-shudrtadsinformation: {min: 2, max: 2}
  eric-hssims-shudrlocationinfo: {min: 2, max: 2}
  eric-hssims-shudrstnsr: {min: 2, max: 2}
  eric-hssims-shudruesrvcccapability: {min: 2, max: 2}
  eric-hssims-shpur: {min: 2, max: 2}
  eric-hssims-shsnr: {min: 2, max: 2}
  eric-hssims-soap: {min: 2, max: 2}
  eric-hssims-shprovnotification: {min: 2, max: 2}
  eric-hssims-shpnr: {min: 2, max: 2}
  eric-hssims-shdiameter: {min: 2, max: 2}
  eric-hssims-cxdiameter: {min: 2, max: 2}
  eric-hssims-cxlir: {min: 2, max: 2}
  eric-hssims-cxuar: {min: 2, max: 2}
  eric-hssims-cxmar: {min: 2, max: 2}
  eric-hssims-cxsarreg: {min: 2, max: 2}
  eric-hssims-cxsardereg: {min: 2, max: 2}
  eric-hssims-cxsarunreg: {min: 2, max: 2}
  eric-hssims-cxsarauth: {min: 2, max: 2}
  eric-hssims-cxprovnotifrtr: {min: 2, max: 2}
  eric-hssims-cxrtr: {min: 2, max: 2}
  eric-hssims-cxprovnotifppr: {min: 2, max: 2}
  eric-hssims-cxppr: {min: 2, max: 2}
  eric-hssims-capacity: {min: 1, max: 20}
  eric-hssims-cxsarnoassign: {min: 2, max: 2}
  eric-hssepc-s6aprovnotification: {min: 2, max: 2}
  eric-hssepc-swxrtr: {min: 2, max: 2}
  eric-hssepc-swxprovnotification: {min: 2, max: 2}
  eric-udm-eeamfingressnotif: {min: 2, max: 2}
  eric-udm-eeegressnotif-reach-for-sms: {min: 2, max: 2}
  eric-udm-eeegressnotif-roaming-status: {min: 2, max: 2}
  eric-udm-eeegressnotif-supi-pei-indiv: {min: 2, max: 2}
  eric-udm-eeegressnotif-supi-pei-anyue: {min: 2, max: 2}
