vnflcm:
  vnfInstanceName: node299-cluster1-ccsm1
  vnfProductName: CCSM
  vnfSoftwareVersion: 1.21.15
  instantiate-file: instantiate.json
  values-file: values.yaml
  namespace: ccsm1
  evnfmName: n299
  csar-url: https://arm.seli.gic.ericsson.se/artifactory/proj-hss-docker-global/proj_hss/5g/releases/csar/drop94/Ericsson.CCSM.CXP9037722_1_21_15_1.csar
access-info:
  oam: ccsm1-oam.node299-cluster1.sero.gic.ericsson.se
  ldap-admin:
    user: sysadmin
    pass: c3lzQWRtMW5ARGF5MA==
  users:
  - user: ccsm-admin
    pass: RG01R0NAUzBsdXQhb24=
    pass-init: Q2hhbmdlbWVAMXN0
  - user: ccsm-sec
    pass: RG01R0NAUzBsdXQhb24=
    pass-init: Q2hhbmdlbWVAMXN0
pipeline:
- module: create-namespace
- module: create-k8s-secret
  name: eric-sec-ldap-server-creds
  sources:
  - type: literal
    key: adminuser
    value: sysadmin
  - type: literal
    key: passwd
    value: sysAdm1n@Day0
  - type: literal
    key: adminpasswd
    value: $6$fzLPYlRZCpweJMJC$AiNfP0WYE3npY8Za6GxMFoGj75TOl.TS6tmnnky2Bv5wY0Ek8RIoJlr9pyj0LF3wMMaNsNTUH4jp2lIHviJGS0
- module: create-k8s-secret
  name: eric-data-distributed-coordinator-creds
  sources:
  - type: literal
    key: etcdpasswd
    value: sysAdm1n@Day0
- module: instantiate
- module: verify-pod-running
  ignore-not-running:
  - eric-data-search-engine-curator
- module: run-k8s-command
  name: Create networkpolicy to allow accessing eric-pm-server and eric-data-search-engine
  cmd: |
    apply -f {file1}
    apply -f {file2}
  inline-files:
    file1: network-policy/eric-pm-server-allow.yaml
    file2: network-policy/eric-data-search-engine-allow.yaml
- module: run-k8s-command
  name: Create pm server ingress
  cmd: create ingress eric-pm-server --rule="eric-pm-server-ccsm1.ingress.node299-cluster1.sero.gic.ericsson.se/*=eric-pm-server:9090"
- module: verify-pod-ready
  check-interval: 5
  deployments:
  - eric-cm-yang-provider
- module: load-cmyp-user-config
  file: user-config.xml
  proto: netconf
  retry-interval: 30
- module: sleep
  duration: 300
- module: change-initial-password
- module: load-cmyp-app-config
  file: external-certificates.xml
  user-id: 1
  proto: netconf
- module: sleep
  duration: 15
- module: load-cmyp-app-config
  file: nrfagent-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 15
- module: load-cmyp-app-config
  file: ausf-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 15
- module: load-cmyp-app-config
  file: udm-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 15
- module: load-cmyp-app-config
  file: avg-config/1-seed-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 15
- module: load-cmyp-app-config
  file: avg-config/2-customerkey-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 15
- module: load-cmyp-app-config
  file: avg-config/3-arpf-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 15
- module: load-cmyp-app-config
  file: avg-config/4-hnkey-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 15
- module: load-cmyp-app-config
  file: avg-config/5-a4key-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 15
- module: load-cmyp-app-config
  file: avg-config/6-fset-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 15
- module: load-cmyp-app-config
  file: hss-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 15
- module: load-cmyp-app-config
  file: ccsm-sctp-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 15
- module: load-cmyp-app-config
  file: hssepc-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 15
- module: load-cmyp-app-config
  file: hss-remote-nf-profile.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 15
- module: load-cmyp-app-config
  file: udm-remote-nf-profile.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 15
- module: load-cmyp-app-config
  file: diameter-epc-s6a-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 15
#- module: load-cmyp-app-config
#  file: diameter-eir-s13-config.xml
#  user-id: 0
#  proto: netconf
#- module: sleep
#  duration: 15
#- module: load-cmyp-app-config
#  file: eir-config.xml
#  user-id: 0
#  proto: netconf
#- module: sleep
#  duration: 15
- module: load-cmyp-app-config
  file: ddc-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 15
- module: load-cmyp-app-config
  file: cm-hssims-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 15
- module: load-cmyp-app-config
  file: snmp-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 60
#- module: run-external-script
#  script-path: /lab/pccc_utils/scripts/sputils
#  args: horseKeeper -k node279-cluster1 -n ccsm1 --patch-grafana-ds --cnf-max-buckets 262143 --fivegc-cnfs-healthcheck
