# general settings
global:
  timezone: CET
  domainName: sero.gic.ericsson.se
  clusterName: eda2.n84-eccd3
  ericsson:
    licensing:
      licenseDomains:
        - productType: EDA
          customerId: 946060
          swltId: STA-EDA-1
  activation:
    service:
      prov:
        annotations:
          metallb.universe.tf/allow-shared-ip: eda-oam
          metallb.universe.tf/address-pool: eda-oam
      oam:
        annotations:
          metallb.universe.tf/allow-shared-ip: eda-oam
          metallb.universe.tf/address-pool: eda-oam
#ingress:
#  oam:
#    secret: eda-oam-tlscrt
#  prov:
#    secret: eda-prov-tlscrt

eric-tm-ingress-controller-cr:
  service:
    annotations:
      sharedVIPLabel: eda-oam
      addressPoolName: eda-oam

eric-fh-snmp-alarm-provider:
  service:
    annotations:
      sharedVIPLabel: eda-oam
      addressPoolName: eda-oam

eric-data-wide-column-database-cd:
  persistence:
    dataVolume:
      persistentVolumeClaim:
        storageClassName: network-block
        size: 30G


eric-data-message-bus-kf:
  persistence:
    persistentVolumeClaim:
      storageClassName: network-block

eric-data-document-database-pg:
  persistentVolumeClaim:
    storageClassName: network-block

eric-data-search-engine:
  persistence:
    data:
      persistentVolumeClaim:
        storageClassName: network-block
    master:
      persistentVolumeClaim:
        storageClassName: network-block

eric-act-activation-engine:
  statefulset:
    storageClass: network-block

eric-data-coordinator-zk:
  persistence:
    persistentVolumeClaim:
      storageClassName: network-block

eric-data-distributed-coordinator-ed:
  persistence:
    persistentVolumeClaim:
      storageClassName: network-block

eric-cnom-document-database-mg:
  persistence:
    storageClass: network-block

eric-ctrl-bro:
  persistence:
    persistentVolumeClaim:
      storageClassName: network-block

eric-pm-server:
  server:
    persistentVolume:
      storageClass: network-block

eric-lm-combined-server:
  licenseServerClient:
    licenseServer:
      thrift:
        host: 10.221.14.88
        port: 9095
