global:
  registry:
    url: registry.eccd.local:5000
  security:
    tls:
      enabled: false
imageCredentials:
  repoPath: ""
images:
  configmapReload:
    name: eric-pm-configmap-reload
    tag: 2.4.0-22-7f3c94f0
  initChownData:
    name: eric-pm-initcontainer
    tag: 2.4.0-22-7f3c94f0
  server:
    name: eric-pm-server
    tag: 2.4.0-22-7f3c94f0
rbac:
  appMonitoring:
    configFileCreate: false
    enabled: false
resources:
  server:
    limits:
      cpu: "8"
      memory: 16Gi
server:
  configMapOverrideName: eric-pm-server-ccd
  extraSecretMounts:
  - defaultMode: 420
    mountPath: /var/run/secrets/etcd/client
    name: etcd-certs
    readOnly: true
    secretName: etcd-certs
  retention: 15d
  persistentVolume:
    enabled: true
    size: 150Gi
  serviceAccountName: eric-pm-server
