global:
  createClusterRoles: true
  hosts:
    gas: 'oss.evnfm1.n89-eccd1.sero.gic.ericsson.se'
    gr: ''
    iam: 'iam.evnfm1.n89-eccd1.sero.gic.ericsson.se'
    vnfm: 'eo-nbi.evnfm1.n89-eccd1.sero.gic.ericsson.se'
  registry:
    password: 'admin123'
    url: 'registry.node89.sero.gic.ericsson.se'
    username: 'admin'
  support:
    ipv6:
      enabled: false
  timezone: CET
  ericsson:
    licensing:
      licenseDomains:
      - productType: 'Ericsson_Orchestrator'
        swltId: 'STA-EVNFM-14'
        customerId: '946060'
      nelsConfiguration:
        primary:
          hostname: 'nelsaas-vnf1-thrift.sero.gic.ericsson.se'
tags:
  eoCm: false
  eoEvnfm: true
  eoVmvnfm: true
eric-cloud-native-base:
  eric-ctrl-bro:
    persistence:
      persistentVolumeClaim:
        size: 20Gi
    sftp:
      password: 'Qwerasdf1234!'
      username: 'vnfm'
  eric-data-search-engine:
    service:
      network:
        protocol:
          IPv6: false
  eric-sec-access-mgmt:
    accountManager:
      enabled: false
      inactivityThreshold: 9999
    replicaCount: 2
  eric-log-transformer:
    egress:
      syslog:
        enabled: false
        tls:
          enabled: true
        remoteHosts: []
  eric-data-object-storage-mn:
    persistentVolumeClaim:
      size: 10Gi
  eric-fh-snmp-alarm-provider:
    sendAlarm: false
  eric-lm-combined-server:
    licenseServerClient:
      licenseServer:
        thrift:
          host: 'nelsaas-vnf1-thrift.sero.gic.ericsson.se'
geo-redundancy:
  enabled: false
eric-oss-common-base:
  service-mesh-ingress-gateway:
    service:
      loadBalancerIP: '10.221.124.85'
      annotations:
        cloudProviderLB: {}
  sessionTokens:
    maxSessionDurationSecs: 36000
    maxIdleTimeSecs: 1800
  eric-gr-bur-orchestrator:
    credentials:
      username: ''
      password: ''
    gr:
      bro:
        autoDelete:
          backupsLimit: 10
      sftp:
        url: ''
        username: ''
        password: ''
      cluster:
        role: ''
        secondary_hostnames:
        - ''
      registry:
        secondarySiteContainerRegistryHostname: ''
  system-user:
    credentials:
      username: 'system-username'
      password: 'DefaultP123456!'
  gas:
    defaultUser:
      username: 'gas-user'
      password: 'DefaultP123456!'
  eric-eo-usermgmt:
    replicaCount: 2
  eric-eo-usermgmt-ui:
    replicaCount: 2
eric-oss-function-orchestration-common:
  eric-eo-evnfm-nbi:
    eric-evnfm-rbac:
      defaultUser:
        username: 'vnfm'
        password: 'Qwerasdf1234!'
  eric-am-onboarding-service:
    container:
      registry:
        enabled: true
    resources:
      limits:
        memory: 32Gi
    userSecret: container-credentials
eric-eo-evnfm:
  services:
    onboarding:
      enabled: true
  eric-am-common-wfs:
    helm:
      url: ''
    dockerRegistry:
      secret: null
    userSecret: container-credentials
  eric-lcm-container-registry:
    enabled: true
    highAvailability: false
    ingress:
      hostname: 'docker-registry.evnfm1.n89-eccd1.sero.gic.ericsson.se'
    persistence:
      persistentVolumeClaim:
        size: 450Gi
  eric-global-lcm-container-registry:
    hostname: ''
    username: ''
    password: ''
  eric-lcm-helm-chart-registry:
    ingress:
      enabled: false
      hostname: 'helm-registry.evnfm1.n89-eccd1.sero.gic.ericsson.se'
    env:
      secret:
        BASIC_AUTH_USER: 'vnfm'
        BASIC_AUTH_PASS: 'Qwerasdf1234!'
  eric-vnfm-orchestrator-service:
    oss:
      topology:
        secretName: null
    smallstack:
      application: true
eric-eo-evnfm-vm:
  eric-vnflcm-service:
    oss:
      secretName: null
    persistentVolumeClaim:
      size: 20Gi
    service:
      enabled: false
      loadBalancerIP: '::'
      externalTrafficPolicy: Local
    ha:
      enabled: false
      persistentVolumeClaim:
        storageClassName: ''
