global:
  timezone: CET
  applicationId: eric-n67-pcg001
  ericsson:
    licensing:
      licenseDomains:
        - productType: 'PACKET_CORE_GATEWAY'
          customerId: '946060'
          swltId: 'STA-SC-3'


eric-pc-kvdb-rd-server:
  numberOfMaster: 5
  server:
    maxMemory: 5120mb

eric-cm-yang-provider:
  service:
    annotations:
      addressPoolName: pcg-oam
      sharedVIPLabel: pcg-oam

eric-data-search-engine:
  replicaCount:
     data: 3
  persistence: 
    data: 
      persistentVolumeClaim: 
        size: "50Gi" 
  resources:
    data:
      limits:
        memory: "10Gi"

snmp-alarm-provider-secret-creation:
  enabled: false
eric-fh-snmp-alarm-provider:
  nodeSelector:
    snmp-sender: eric-pcg
  service:
    annotations:
     addressPoolName: pcg-oam
     sharedVIPLabel: pcg-oam
    secretName: snmp-alarm-provider-config
  oamVIP:
    enabled: true
    vip: 10.136.11.236
    destIp: 11.0.18.3

eric-odca-diagnostic-data-collector:
  resources:
    diagnostic-data-collector:
      limits:
        memory: 32Gi
        cpu: 2000m
        ephemeral-storage: 30Gi
      requests:
        memory: 800Mi
        cpu: 1600m
        ephemeral-storage: 24Gi

eric-pc-routing-engine:
  interfaces:
    type: macvlan
    macvlan:
      - master: eth1

eric-pc-up-data-plane:
  allowNetworkConfigChanges: true
  annotations:
    k8s.v1.cni.cncf.io/networks: eric-pc-up-data-plane-net1, eric-pc-up-data-plane-net2
  replicaCount: 12
  acceleratedIo:
    enabled: true
    driver: bifurcated
  applications:
  - name: app100
  deployment:
    pinThreads: true
  nodeSelector:
    type: high-throughput
  resources:
    dataPlane:
      limits:
        cpu: 12
        hugepages-1Gi: 1Gi
        memory: 24Gi
      requests:
        cpu: 12
        hugepages-1Gi: 1Gi
        memory: 24Gi
  interfaces:
    - name: net1
      type: host-device
      resourceName: 'intel.com/dp_sriov_mlx5_left'
    - name: net2
      type: host-device
      resourceName: 'intel.com/dp_sriov_mlx5_right'

  tolerations:
  - effect: NoSchedule
    key: high-throughput
    operator: Equal
    value: "true"

eric-pc-up-pfcp-endpoint:
  cm_source_env: false
  replicaCount: 4
  podDisruptionBudget:
    minAvailable: 75%
  global:
    serviceNames:
      cm:
        mediator: ""
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 30
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 30

eric-pm-server:
  rbac:
    appMonitoring:
      configFileCreate: false
      enabled: true
  server:
    persistentVolume:
      enabled: true
      size: 64Gi
  resources:
    server:
      limits:
        memory: 8192Mi


eric-cnom-server:
  service:
    type: LoadBalancer
  annotations:
    metallb.universe.tf/address-pool: pcg-oam
    metallb.universe.tf/allow-shared-ip: pcg-oam

eric-data-sftp-server:
  service:
    annotations:
      sharedVIPLabel: "pcg-oam"
      addressPoolName: "pcg-oam"

eric-sec-ldap-server:
  adminCredentials:
    adminuser: day0
    adminpasswd: "$6$<0>$AcnhaMbmO6zVPekh7UpnvZbfwMKm7dALF2hvlWG3/ZI2S8onY.c3UD3CBjbiqidN4.Luz8biX1qneoCD.JTm90"



eric-log-transformer:
  jvmHeap: 4000m
  replicaCount: 3
  resources:
    logtransformer:
      limits:
        cpu: 2000m
        memory: 6Gi
      requests:
        cpu: 2000m
        memory: 6Gi

eric-lm-combined-server:
  licenseServerClient:
    licenseServer:
      thrift:
        host: 10.221.14.88
        port: 9095
