pre_install:
    - name: disable_puppet_due_to_PCGW-4936
      executable: "/usr/bin/puppet agent"
      arg: "--disable 'Disable puppet Dallas 1 installed - PCGW-4936'"
      host: [selnpctool-1298-01-102,selnpctool-1298-01-101,selnpctool-1298-01-201,selnpctool-1298-01-202]

    - name: bind_dpdk
      executable: "/lab/testtools/dallas/rhel664/Release/3R116B04/3pp/ltt/dpdk/lts_bind_dpdk"
      arg: "/var/dallas/tap.conf"
      host: [selnpctool-1298-01-201,selnpctool-1298-01-202]
      debug: on

post_install:
   # - name: print_memory
     #executable: "/lab/epg_scm4_builds/program/ci/EPG_28R46Z01/epgcats/bin/dpdk-procinfo.sh"
     # executable: "/lab/epg_scm4_builds/program/ci/EPG_28R55VA01/epgcats/bin/dpdk-procinfo.sh"      
     # arg: "'default output /var/log/ltt_memory.log'"
     # host: [selnpctool-1298-01-201,selnpctool-1298-01-202]

    - name: add routes
      executable: "/root/add_nonltt_route.sh"
      host: [selnpctool-1298-01-102,selnpctool-1298-01-101,selnpctool-1298-01-201,selnpctool-1298-01-202]
      debug: on


post_uninstall:
    - name: unbind_dpdk
      executable: "/lab/testtools/dallas/rhel664/Release/3R116B04/3pp/ltt/dpdk/lts_unbind_dpdk"      
      host: [selnpctool-1298-01-201,selnpctool-1298-01-202]


    - name: enable_puppet
      executable: "/usr/bin/puppet agent"
      arg: "--enable"
      host: [selnpctool-1298-01-102,selnpctool-1298-01-101,selnpctool-1298-01-201,selnpctool-1298-01-202]

    - name: run_puppet
      executable: "/usr/sbin/call_home || true"
      host: [selnpctool-1298-01-102,selnpctool-1298-01-101,selnpctool-1298-01-201,selnpctool-1298-01-202]
      debug: on

