configmap:
  data: |
    {
       "resourceList": [{
                "resourceName": "intel_sriov_left",
                 "selectors": {
                     "vendors": ["8086"],
                     "pfNames": ["ens1f0"],
                     "drivers": ["i40evf", "ixgbevf", "iavf"]
                 }
             },
             {
                 "resourceName": "intel_sriov_right",
                 "selectors": {
                     "vendors": ["8086"],
                     "pfNames": ["ens1f1"],
                     "drivers": ["i40evf", "ixgbevf", "iavf"]
                 }
             },
             {
                "resourceName": "intel_sriov_dpdk_left",
                "selectors": {
                    "vendors": ["8086"],
                    "pfNames": ["ens1f0"],
                    "drivers": ["vfio-pci", "igb_uio"]
                }
            },
            {
                "resourceName": "intel_sriov_dpdk_right",
                "selectors": {
                    "vendors": ["8086"],
                    "pfNames": ["ens1f1"],
                    "drivers": ["vfio-pci", "igb_uio"]
                }
            }
        ]
    }
  name: sriov-dp-configmap
container:
  name: kube-sriovdp
image:
  name: sriov-network-device-plugin
  repo: registry.eccd.local:5000
  tag: v3.3.1-6-e10972a4
kube_namespace: kube-system
nodeSelector:
  node-role.kubernetes.io/worker: worker
  type: high-throughput
tolerations:
- key: high-throughput
  effect: "NoSchedule"
  value: "true"
