global:
  timezone: CET
  ericsson:
    licensing:
      licenseDomains:
        - productType: PACKET_CORE_GATEWAY
          customerId: 946060
          swltId: STA-PCG-20


eric-pc-kvdb-rd-server:
  numberOfMaster: 7

eric-pc-routing-engine:
  interfaces:
    type: ovs
    ovs:
    - bridge: br_data
      vlan_mode: trunk
      trunk:
        - minID: 2202
          maxID: 2202
        - minID: 2205
          maxID: 2205
        - minID: 2204
          maxID: 2204
        - minID: 2201
          maxID: 2201
      mtu: 9000

eric-pc-up-data-plane:
  replicaCount: 24
  acceleratedIo:
    enabled: true
    driver: bifurcated
  applications:
  - name: app100
  nodeSelector:
    type: high-throughput
  resources:
    dataPlane:
      limits:
        cpu: 12
        hugepages-1Gi: 1Gi
        memory: 18Gi
        mellanox.com/mlnx_left: "1"
        mellanox.com/mlnx_right: "1"
      requests:
        cpu: 12
        hugepages-1Gi: 1Gi
        memory: 18Gi
        mellanox.com/mlnx_left: "1"
        mellanox.com/mlnx_right: "1"
  interfaces:
    - name: net1
      type: sriov
      resourceName: mellanox.com/mlnx_left
    - name: net2
      type: sriov
      resourceName: mellanox.com/mlnx_right
  tolerations:
  - effect: NoSchedule
    key: high-throughput
    operator: Equal
    value: "true"

eric-pc-up-pfcp-endpoint:
  replicaCount: 8

snmp-alarm-provider-secret-creation:
  enabled: false

eric-cloud-native-base:
  eric-si-application-sys-info-handler:
    asih:
      applicationId: n189-pcg1

  eric-fh-snmp-alarm-provider:
    service:
      annotations:
        addressPoolName: pcg1-oam
        sharedVIPLabel: pcg1-oam
#delete it due to PCSOLCI-2484 fix this
#      secretName: eric-pc-gateway-snmp-alarm-provider-config
      oamVIP:
        enabled: false

  eric-log-transformer:
    replicaCount: 3

  eric-data-search-engine:
    autoSetRequiredWorkerNodeSysctl: false

  eric-odca-diagnostic-data-collector:
    resources:
      # According to CPI for any number of DP pods
      diagnostic-data-collector:
        limits:
          memory: 1Gi
          cpu: 1500m
          ephemeral-storage: 25Gi

  eric-pm-server:
    rbac:
      appMonitoring:
        configFileCreate: false
        enabled: true
    server:
      persistentVolume:
        enabled: true
        size: 36Gi
    resources:
      # According to CPI for 18 DP pods
      eric-pm-server:
        limits:
          cpu: 3
          memory: 12Gi
        requests:
          cpu: 1500m
          memory: 8Gi

  eric-lm-combined-server:
    licenseServerClient:
      licenseServer:
        thrift:
          host: nelsaas-vnf1-thrift.sero.gic.ericsson.se
          port: 9095

  eric-dst-agent:
    tolerations:
      - key: "high-throughput"
        value: "true"
        operator: Equal
        effect: NoSchedule

  eric-log-shipper:
    tolerations:
      - key: "high-throughput"
        value: "true"
        operator: Equal
        effect: NoSchedule

eric-cloud-native-nf-additions:
  eric-cm-yang-provider:
    service:
      annotations:
        addressPoolName: pcg1-oam
        sharedVIPLabel: pcg1-oam

  eric-data-sftp-server:
    service:
      annotations:
        sharedVIPLabel: "pcg1-oam"
        addressPoolName: "pcg1-oam"

  eric-sec-ldap-server:
    adminCredentials:
      adminuser: sysadmin
      adminpasswd: "$6$k1.3Zq5dDJTfGK.W$hxgSMANS35.6qN1NTnEnn3kp4rdD81QpMreWNiFItp8esUUsGll.6s0tbJr33YlKbUz4cTn8zjZPSpOf69bSg0"

cnom-loadBalancer-service:
  enabled: true
  annotations:
    metallb.universe.tf/address-pool: "pcg1-oam"
    metallb.universe.tf/allow-shared-ip: "pcg1-oam"
