vnflcm:
  vnfInstanceName: node299-cluster1-ccdm1
  vnfProductName: ERIC-CCDM
  vnfSoftwareVersion: 1.11.26+1
  instantiate-file: instantiate.json
  values-file: values.yaml
  namespace: ccdm1
  evnfmName: n299
  csar-url: https://arm.seli.gic.ericsson.se/artifactory/proj-5g-ccdm-released-generic-local/CCDM/Ericsson.CCDM.CXP9037622_1_11_26_1.csar
access-info:
  oam: ccdm1-oam.node299-cluster1.sero.gic.ericsson.se
  ldap-admin:
    user: sysadmin
    pass: c3lzQWRtMW5ARGF5MA==
  users:
  - user: ccdm-admin
    pass: RG01R0NAUzBsdXQhb24=
    pass-init: Q2hhbmdlbWVAMXN0
  - user: ccdm-sec
    pass: RG01R0NAUzBsdXQhb24=
    pass-init: Q2hhbmdlbWVAMXN0
pipeline:
- module: run-k8s-command
  name: Create ccdm-kvdb-priorityclass to assign a higher priority to this microservice
  cmd: |
    apply -f {file1}
  inline-files:
    file1: ccdm-kvdb-priorityclass.yaml
- module: create-namespace
- module: create-k8s-secret
  name: eric-sec-ldap-server-creds
  sources:
  - type: literal
    key: adminuser
    value: sysadmin
  - type: literal
    key: passwd
    value: sysAdm1n@Day0
  - type: literal
    key: adminpasswd
    value: $6$fzLPYlRZCpweJMJC$AiNfP0WYE3npY8Za6GxMFoGj75TOl.TS6tmnnky2Bv5wY0Ek8RIoJlr9pyj0LF3wMMaNsNTUH4jp2lIHviJGS0
- module: create-k8s-secret
  name: eric-sec-certm-deployment-configuration
  sources:
  - type: file
    key: eric-sec-certm-deployment-configuration.json
    file: eric-sec-certm-deployment-configuration.json
- module: create-k8s-secret
  name: eric-sec-admin-user-management-day0-external-ldap
  sources:
  - type: file
    key: ldap-configuration.json
    file: ldap-configuration.json
- module: create-k8s-secret
  name: snmp-alarm-provider-config
  sources:
  - type: file
    key: config.json
    file: snmp-config.json
- module: create-k8s-secret
  name: eric-data-distributed-coordinator-creds
  sources:
  - type: literal
    key: etcdpasswd
    value: sysAdm1n@Day0
- module: create-k8s-secret
  name: eric-sec-access-mgmt-creds
  sources:
  - type: literal
    key: kcadminid
    value: admin
  - type: literal
    key: kcpasswd
    value: sysAdm1n@Day0
- module: instantiate
- module: verify-pod-running
  ignore-not-running:
  - eric-data-search-engine-curator
  - eric-udr-app-counters
  - eric-udr-bulk-data-synchronizer
  - eric-udr-cmmanager
  - eric-udr-consistency-check-orchestrator
  - eric-udr-dbmanager
  - eric-udr-dbmonitor
  - eric-udr-gudrestfe
  - eric-udr-import-export-orchestrator
  - eric-udr-ldap-balancer
  - eric-udr-ldapfe
  - eric-udr-migration-orchestrator
  - eric-udr-migration-task
  - eric-udr-notificationsubscription
  - eric-udr-nrfproxy
  - eric-udr-nudrfe
  - eric-udr-provisioningfe
  - eric-udr-rest-notifchecker
  - eric-udr-rest-notifsender
  - eric-udr-soap-notifchecker
  - eric-udr-soap-notifsender
  - eric-udr-prov-sync-fe
- module: run-k8s-command
  name: Create networkpolicy to allow accessing eric-pm-server and eric-data-search-engine
  cmd: |
    apply -f {file1}
    apply -f {file2}
  inline-files:
    file1: network-policy/eric-pm-server-allow.yaml
    file2: network-policy/eric-data-search-engine-allow.yaml
- module: run-k8s-command
  name: Create pm server ingress
  cmd: create ingress eric-pm-server --rule="eric-pm-server-ccdm.ingress.node299-cluster1.sero.gic.ericsson.se/*=eric-pm-server:9090"
- module: verify-pod-ready
  check-interval: 5
  deployments:
  - eric-cm-yang-provider
- module: load-cmyp-user-config
  file: user-config.xml
  proto: netconf
  retry-interval: 30
- module: sleep
  duration: 30
- module: change-initial-password
- module: load-cmyp-app-config
  file: external-certificates.xml
  user-id: 1
  proto: netconf
- module: sleep
  duration: 10
- module: load-cmyp-app-config
  file: nrfagent-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 10
- module: load-cmyp-app-config
  file: udr-config.xml
  user-id: 0
  proto: netconf
- module: verify-pod-ready
  check-interval: 30
  deployments:
  - eric-udr-nudrfe
  statefulsets:
  - eric-udr-kvdb-ag-server
- module: sleep
  duration: 10
- module: load-cmyp-app-config
  file: schema/hssepc-schema.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 10
- module: load-cmyp-app-config
  file: schema/hssims-schema.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 10
- module: load-cmyp-app-config
  file: ddc-config.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 10
- module: load-cmyp-app-config
  file: hssepc-application-counters.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 30
- module: load-cmyp-app-config
  file: hssims-application-counters.xml
  user-id: 0
  proto: netconf
- module: sleep
  duration: 30
- module: load-cmyp-app-config
  name: Set udr subscription expire time to 7 days
  user-id: 0
  commands: |-
    config
    udr nudr-dr-notifications maximum-subscription-duration 604800
    commit
    end
- module: sleep
  duration: 10
- module: restore-ccdm-data
  sftp-server: 172.30.32.50
  sftp-path: /root/NF_backups/ccdm/ccdm-data-ims-irat-1.11-300k-4kvdb/ccdm-data/ccdm_ccdm-data
  sftp-user: root
  sftp-pass: bG1jX3hkZw==
  user-id: 0
  udr-status-check:
    check-interval: 15
    api-path-and-status:
      /udr/status: OK
      /udr/reporting/dbManager/status: STARTED
      /udr/reporting/dbMonitor/status: OK
