global:
  timezone: CET
  applicationId: eric-n84-pcg003
  ericsson:
    licensing:
      licenseDomains:
        - productType: 'PACKET_CORE_GATEWAY'
          customerId: '946060'
          swltId: 'STA-SC-3'


eric-pc-kvdb-rd-server:
  numberOfMaster: 5
  server:
    maxMemory: 5120mb

eric-cm-yang-provider:
  service:
    annotations:
      addressPoolName: pcg-oam
      sharedVIPLabel: pcg-oam

eric-data-search-engine:
  replicaCount:
     data: 3
  persistence: 
    data: 
      persistentVolumeClaim: 
        size: "50Gi" 
  resources:
    data:
      limits:
        memory: "10Gi"


eric-fh-snmp-alarm-provider:
  service:
    annotations:
     addressPoolName: pcg-oam
     sharedVIPLabel: pcg-oam
    secretName: snmp-alarm-provider-config
  oamVIP:
    enabled: false

eric-odca-diagnostic-data-collector:
  resources:
    diagnostic-data-collector:
      limits:
        memory: 32Gi
        cpu: 3000m
        ephemeral-storage: 40Gi
      requests:
        memory: 800Mi
        cpu: 1600m
        ephemeral-storage: 24Gi

eric-pc-routing-engine:
  interfaces:
    type: macvlan
    macvlan:
      - master: eth4

eric-pc-up-data-plane:
  replicaCount: 1
  acceleratedIo:
    enabled: true
    driver: bifurcated
  applications:
  - name: app100
  deployment:
    pinThreads: true
  nodeSelector:
    type: high-throughput
  resources:
    dataPlane:
      limits:
        cpu: "14"
        hugepages-1Gi: 1Gi
        memory: 18Gi
        intel.com/intel_sriov_dpdk_left: "1"
        intel.com/intel_sriov_dpdk_right: "1"
      requests:
        cpu: "14"
        hugepages-1Gi: 1Gi
        memory: 18Gi
        intel.com/intel_sriov_dpdk_left: "1"
        intel.com/intel_sriov_dpdk_right: "1"

  tolerations:
  - effect: NoSchedule
    key: high-throughput
    operator: Equal
    value: "true"

eric-pc-up-pfcp-endpoint:
  resources:
    pfcpEndpoint:
      requests:
        cpu: 400m
        memory: 8Gi
      limits:
        cpu: '1'
        memory: 8Gi
  
  cm_source_env: false
  replicaCount: 2
  podDisruptionBudget:
    minAvailable: 75%
  global:
    serviceNames:
      cm:
        mediator: ""
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 30
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 30

eric-pm-server:
  rbac:
    appMonitoring:
      configFileCreate: false
      enabled: true
  server:
    persistentVolume:
      enabled: true
      size: 64Gi
  resources:
    eric-pm-server:
      limits:
        cpu: "3"
        memory: 32Gi
      requests:
        cpu: 250m
        memory: 8192Mi

eric-cnom-server:
  service:
    type: LoadBalancer
  annotations:
    metallb.universe.tf/address-pool: pcg-oam
    metallb.universe.tf/allow-shared-ip: pcg-oam

eric-data-sftp-server:
  service:
    annotations:
      sharedVIPLabel: "pcg-oam"
      addressPoolName: "pcg-oam"


eric-sec-ldap-server:
  adminCredentials:
    adminuser: day0
    adminpasswd: "$6$<0>$AcnhaMbmO6zVPekh7UpnvZbfwMKm7dALF2hvlWG3/ZI2S8onY.c3UD3CBjbiqidN4.Luz8biX1qneoCD.JTm90"
eric-pc-up-partitioner:
  resources:
    partitioner:
      requests:
        cpu: 200m
        memory: 40Mi
        ephemeral-storage:
      limits:
        cpu: '1'
        memory: 8Gi
        ephemeral-storage:


eric-log-transformer:
  jvmHeap: 4000m
  replicaCount: 2
  resources:
    logtransformer:
      limits:
        cpu: 2000m
        memory: 6Gi
      requests:
        cpu: 2000m
        memory: 6Gi

eric-cm-mediator:
  resources:
    eric-cm-mediator:
      limits:
        memory: 1024Mi
eric-pc-up-br-agent:
  resources:
    brAgent:
      limits:
        memory: 512Mi


eric-data-object-storage-mn:
  server:
    resources:
      limits:
        memory: 2048Mi


eric-lm-combined-server:
  licenseServerClient:
    licenseServer:
      thrift:
        host: 10.221.14.88
        port: 9095
