# CCDM single instance is only supported for the small-system profile.
systemProfile: 'standard'

nodeName: n84-ccdm1
nodeType: ERIC-CCDM
clusterName: ccdm1.n84

vnflcm:
  clusterName: n84-eccd1
  namespace: ccdm
  InstantiateVnfRequest:
    applicationTimeOut: 3600
    skipVerification: "true"

users:
  day0:
    username: sysadmin
    password: Pa$$w0rd4LDAP
  day1:
  - username: ccdmoam
    password: Changeme@1st
    groups:
    - udr-admin
    - pf-admin
    - pf-operator
    - nrfagent-admin
    - system-admin
  - username: ccdmsec
    password: Changeme@1st
    groups:
    - udr-security-admin
    - nrfagent-security-admin
    - system-security-admin


license:
  customerId: "946060"
  swltId: STA-CCDM-12

oamVip: 214.14.170.98

soapNotifyHost: udm1.n84

#Remove multiSite but reserve siteId: 1
siteId: 1

ddc:
  remotePath: /home/admin/ddc/eccd1/n84-ccdm1

#Add ccdm outer udr and geored
ccdm:
  udr:
    host: udr1.n84
    port: 443
    instanceId: f8b5865c-49e8-463e-8f16-99eccd1d3f41
    geored:
      local: 
        provisioning-priority: 3
        host: udr1-intersite.n84

clients:
- client: mapi-client
  secret: mapi-secret
  groups:
  - scopes.ericsson.com/activation/mapi.read
  - scopes.ericsson.com/activation/mapi.write
- client: replay-client
  secret: replay-secret
  groups:
  - scopes.ericsson.com/activation/mapi.write
  - scopes.ericsson.com/activation/replay.callback

replicaCount:
  eric-ingressgw-eda-provisioning: 6
  eric-ingressgw-udr-ldap-traffic: 12
  eric-ingressgw-udr-ldap-provisioning: 8
  eric-ingressgw-udr-traffic: 12
  eric-ingressgw-udr-intersite: 10

#Remove parameter 'minReplica' and 'maxReplica', using hpaReplica[max, min] to replace
hpaReplica:
  eric-udr-prov-sync-fe:
    max: 100
    min: 2
  eric-udr-nudrsvc:
    max: 100
    min: 2
  eric-udr-notificationsubscription:
    max: 100
    min: 2
  eric-udr-gudrestfe:
    max: 100
    min: 2
  eric-udr-provisioningfe:
    max: 100
    min: 2
  eric-udr-ldapfe:
    max: 100
    min: 2
  eric-udr-ldap-balancer:
    max: 6
    min: 6
  eric-udr-rest-notifchecker:
    max: 100
    min: 2
  eric-udr-rest-notifsender:
    max: 100
    min: 2
  eric-udr-soap-notifchecker:
    max: 100
    min: 2
  eric-udr-soap-notifsender:
    max: 100
    min: 2

#Storage['eric-ctrl-bro'] change to pvcSize ['eric-ctrl-bro']
pvcSize:
  eric-ctrl-bro: 128Gi

#Add new parameter vtap[tapagent: true]
vtap:
  tapagent: true

#Add new parameter snmp[sourceIdentifier: "{{CCDM_OAM_VIP}}"]
snmp:
  sourceIdentifier: "214.14.170.98"

#Add new parameter for eric-data-wide-column-database-cd size
#columnDatabaseSize: 70Gi

#Add new parameter consistency
consistency:
  remotePath: ccdm/consistencyreport

