######################################
## CNF general information
######################################
nodeName: n47-eccd1
nodeType: EDA
instance: 1

vnflcm:
  clusterName: eda1-oam.n47-eccd1
  namespace: eda2
  InstantiateVnfRequest:
    applicationTimeOut: 2000
    commandTimeOut: 2000

snmp:
  agentEngineId: 800000c10400000001
  heartbeatInterval: 600

hssValidatorTag: 1.29.102
#users:
#  day0:
#    username: sysadmin
#    password: Pa$$w0rd4LDAP
#
#  day1:
#  - username: ccesoam
#    password: Changeme1st!
#    groups:
#    - nef-admin
#    - apigm-admin
#    - sragent-admin
#    - nrfagent-admin
#    - system-admin
#  - username: ccessec
#    password: Changeme1st!
#    groups:
#    - nef-security-admin
#    - apigm-security-admin
#    - sragent-security-admin
#    - nrfagent-security-admin
#    - system-security-admin

license:
  customerId: "946060"
  swltId: STA-EDA-13

hssValidatorTag: 1.29.102
persistentVolumeClaim:
  eric-data-wide-column-database-cd: 103G
  eric-data-message-bus-kf: 2G
replicaCount:
  eric-act-aaa: 2
  eric-act-inbound-async: 2
  eric-act-inbound-interfaces: 2
  eric-act-inbound-mml: 2
  eric-act-rest-provisioning: 2
  eric-act-tomcat: 2

ne:
  ccdm:
    ldap:
      host: 214.13.224.143
    mapi:
      host: 214.13.224.132
      oauthTokenHost: n47-ccdm.sero.gic.ericsson.se
  ccsm:
      host: 214.13.224.133
