global:
  timezone: CET
  applicationId: n189-pcc
  ericsson:
    licensing:
      licenseDomains:
        - productType: PACKET_CORE_CONTROLLER
          customerId: 946060
          swltId: STA-PCC-9
  probe:
    enabled: false
  licensing:
    sites:
      - hostname: nelsaas-vnf1-thrift.sero.gic.ericsson.se
        port: 9095
  logShipper:
    deployment:
      type: "daemonset"
  service:
    endpoints:
      kvdbClients:
        tls:
          enforced: required
  hooklauncher:
    executor: integration
    executorCharts:
      - eric-pc-controller

  sm:
    pgw:
      enabled: true
    sgw:
      enabled: true
    smf:
      enabled: true

############by default prob is enabled, disable prob manually
eric-probe-event-report-broker:
  enabled: false
  replicaCount: 2
  staticConfig:
    eventReporting:
      streamConsumer:
        - name: ebm-server1
          address: <10.5.5.68>
          port: 8090
          domain: ["pc-mm", "pc-sm"]
          amfEvents: ["activate", "l-attach", "l-cdma2000"]
          smfEvents: ["gx-terminate", "pdp-context-deletion"]
      fileConsumer:
        interval: 15
        domain: ["pc-mm"]
        amfEvents: ["l-attach", "l-cdma2000"]

snmp-alarm-provider-secret-creation:
  enabled: false

eric-pc-routing-engine:
  interfaces:
    type: ovs
    ovs:
    - bridge: br_data
      vlan_mode: trunk
      mtu: 9000
      trunk:
        - minID: 2102 # sig_cn
          maxID: 2102 # sig_cn
        - minID: 2101 # media_cn
          maxID: 2101 # media_cn
        - minID: 2110 # vpngw_intraForward
          maxID: 2110 # vpngw_intraForward

eric-pc-mm:
  global:
    pcmm:
      service:
        useK8sNwSBI: true
        sbi:
          loadBalancerIP: 172.17.128.1
  eric-pc-mm-controller:
    nodeSelector:
      pcc-mm-pod: controller
    adpCm:
      enabled: true
      httpMaxIdleTime: 240000  # 4 minutes
      httpMaxReqLen: 15728640  # 15 MB
    securityContext:
      appArmorProfile: docker-pcc
    appArmorProfile:
      type: localhost
      localhostProfile: docker-pcc

  eric-pc-mm-forwarder:
    nodeSelector:
      pcc-mm-pod: non-controller
    replicaCount: 8
    ipv6: false
    networks:
    - name: ext1
      cniVersion: 0.3.1
      type: ovs
      bridge: br_data
      trunk:
        - "minID": 2001 # MEDIA_CN
          "maxID": 2001 # MEDIA_CN
        - "minID": 2002 # SIG_CN_1
          "maxID": 2002 # SIG_CN_1
        - "minID": 2010 # SIG_CN_2
          "maxID": 2010 # SIG_CN_2
        - "minID": 2004 # RAN_1
          "maxID": 2004 # RAN_1
        - "minID": 2009 # RAN_2
          "maxID": 2009 # RAN_2
        - "minID": 2003 # OM_CN
          "maxID": 2003 # OM_CN
      mtu: 9000
    securityContext:
      appArmorProfile: docker-pcc
    appArmorProfile:
      type: localhost
      localhostProfile: docker-pcc 

  eric-pc-mm-mobility:
    service:
      useK8sNwSBI: true
      sbi:
        type: LoadBalancer
        externalIPv4:
          enabled: true
          loadBalancerIP: 172.17.128.1
    nodeSelector:
      pcc-mm-pod: non-controller
    replicaCount: 19
    securityContext:
      appArmorProfile: docker-pcc
    appArmorProfile:
      type: localhost
      localhostProfile: docker-pcc

  eric-pc-mm-sctp:
    nodeSelector:
      pcc-mm-pod: non-controller
    replicaCount: 8
    securityContext:
      appArmorProfile: docker-pcc
    appArmorProfile:
      type: localhost
      localhostProfile: docker-pcc 

  eric-pc-mm-br-agent:
    nodeSelector:
      pcc-mm-pod: non-controller

  eric-pc-mm-controller-supervisor:
    nodeSelector:
      pcc-mm-pod: non-controller
  

eric-pc-sm:
  eric-pc-sm-diameter:
    nodeSelector:
      pcc-sm-pod: non-controller
  eric-pc-sm-http-client:
    nodeSelector:
      pcc-sm-pod: non-controller
    replicaCount: 3
  eric-pc-sm-ip-allocator:
    nodeSelector:
      pcc-sm-pod: non-controller
  eric-pc-sm-controller:
    nodeSelector:
      pcc-sm-pod: controller

  eric-pc-sm-notification-forwarder:
    nodeSelector:
      pcc-sm-pod: non-controller
    annotations:
      metallb.universe.tf/address-pool: pcc1-smf-notification
      metallb.universe.tf/allow-shared-ip: pcc1-smf-notification

  eric-pc-sm-nsmf-forwarder:
    nodeSelector:
      pcc-sm-pod: non-controller
    services:
      nsmf:
        loadBalancerIP: 172.17.128.2
    replicaCount: 6


  eric-pc-sm-smf-pgw-session:
    replicaCount: 12
    nodeSelector:
      pcc-sm-pod: non-controller

  eric-pc-sm-sgw-session:
    replicaCount: 5
    nodeSelector:
      pcc-sm-pod: non-controller

  eric-pc-sm-br-agent:
    nodeSelector:
      pcc-sm-pod: non-controller

  eric-pc-sm-target-database-master-rd:
    nodeSelector:
      pcc-sm-pod: non-controller

  eric-pc-sm-target-database-replica-rd:
    nodeSelector:
      pcc-sm-pod: non-controller

  eric-pc-sm-udp-forwarder:
    nodeSelector:
      pcc-sm-pod: non-controller
    replicaCount: 3

eric-pc-vpn-gateway-forwarder:
  replicaCount: 4
  resourceName: ovs-cni.network.kubevirt.io/br_data
  resources:
    dataPlane:
      limits:
        ovs-cni.network.kubevirt.io/br_data: 1
      requests:
        ovs-cni.network.kubevirt.io/br_data: 1
  vpnGateway:
    enabled: true
    multiPod: intra
  interfaces:
  - name: net0
    type: ovs
    bridge: br_data
    trunk:
      - "minVlan": 2102 # sig_cn
        "maxVlan": 2102 # sig_cn
      - "minVlan": 2101 # media_cn
        "maxVlan": 2101 # media_cn
      - "minVlan": 2110 # vpngw_intraForward
        "maxVlan": 2110 # vpngw_intraForward
    l2Mtu: 9000



eric-pc-kvdb-rd-server:
  numberOfMaster: 16

eric-lcm-upgrade-sequencer:
  resources:
    lcmupgradesequencer:
      requests:
        memory: "2G"
      limits:
        memory: "2G"

eric-pc-controller-ldap-admin-creds:
  adminCredentials:
    adminuser: day0
    adminpasswd: "$6$lKnqgDXuy.c6qQqt$rn6h/hGp5/MgeS5NE13YSUQFybWUBy7wn9.RotHRr1TItoF4k6hzxDEsWkDHq2JFqMV8Fjju/IJI/hiNiucTO/"

cnom-loadBalancer-service:
  enabled: true
  annotations:
    metallb.universe.tf/address-pool: pcc1-oam
    metallb.universe.tf/allow-shared-ip: pcc1-oam

# Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
eric-pc-pm-init:
  resources:
    pmInit:
      limits:
        cpu: 50m

# Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
eric-pm-resource-monitor:
  resources:
    pmrm:
      requests:
        memory: 128Mi

eric-cloud-native-base:

  eric-si-application-sys-info-handler:
    # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
    resources:
      eric-si-application-sys-info-handler:
        requests:
          memory: 100Mi
    asih:
      applicationId: n189-pcc

  # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
  eric-log-transformer:
    jvmHeap: 4096m
    replicaCount: 5
    resources:
      logtransformer:
        limits:
          cpu: '2'
          memory: 6Gi
        requests:
          memory: 6Gi
      metrics:
        requests:
          memory: 128Mi
      tlsproxy:
        requests:
          memory: 128Mi

  eric-odca-diagnostic-data-collector:
    # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
    resources:
      diagnostic-data-collector:
        requests:
          memory: 1Gi
          cpu: 1000m
          ephemeral-storage: 5Gi
        limits:
          memory: 4Gi
          cpu: 1500m
          ephemeral-storage: 20Gi

  eric-pm-server:
    # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
    persistentVolume:
      size: 32Gi
    resources:
      eric-pm-exporter:
        requests:
          memory: 64Mi
      eric-pm-server:
        limits:
          memory: 12000Mi
        requests:
          memory: 8000Mi

  eric-sec-key-management:
    # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
    resources:
      metrics:
        requests:
          memory: 50Mi

  eric-cm-mediator:
    # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
    resources:
      eric-cm-mediator:
        limits:
          memory: 1Gi
        requests:
          memory: 512Mi

  eric-data-message-bus-kf:
    # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
    resources:
      messagebuskf:
        requests:
          cpu: '2'
          memory: 2Gi

  eric-data-object-storage-mn:
    server:
      # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
      resources:
        limits:
          cpu: 1100m
          memory: 8Gi
        requests:
          cpu: 1100m
          memory: 2Gi
    nodeSelector:
      pcc-sm-pod: non-controller

  eric-fh-snmp-alarm-provider:
    # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
    resources:
      alarmprovider:
        limits:
          memory: 1024Mi
    service:
      annotations:
        sharedVIPLabel: pcc1-oam
        addressPoolName: pcc1-oam
      secretName: snmp-alarm-provider-config
    oamVIP:
      enabled: false

  eric-lm-combined-server:
    licenseServerClient:
      licenseServer:
        thrift:
          host: nelsaas-vnf1-thrift.sero.gic.ericsson.se
          port: 9095
        timer:
          licenseRequestAggregationPeriod: 86400
          peakUsageReportAggregationPeriod: 86400

  # This is a YAML-formatted file used for dimensioning Search Engine.
  # Declare variables to be passed into your templates at deploy time using
  # "--values <path>/search-engine.medium.yaml" during helm install.

  # Configuration of Search Engine
  # Note that the storage size and numbers of replicas for Search Engine affect the retention mechanism provided by Search Engine Curator
  # Use the deployment variants for Search Engine to guarantee intact functionality
  eric-data-search-engine:
  #
  # Custom parameter to disable modification of sysctl by CNFs
    autoSetRequiredWorkerNodeSysctl: false
  #
    replicaCount:
      data: 3
    persistence:
      data:
        persistentVolumeClaim:
          size: "48Gi"
    jvmHeap:
      data: "2048m"
    resources:
      data:
        limits:
          cpu: "1000m"
          memory: "4Gi"
        requests:
          cpu: "1000m"
          memory: "4Gi"

  # Configuration of Search Engine Curator
  # Contains the retention mechanism for different log planes in numbered actions
  # Use the deployment variants for Search Engine to guarantee intact functionality
  eric-data-search-engine-curator:
    actions: |
      1:
        action: delete_indices
        description: >-
          Delete indices older than 7 days (based on index name), for pc-sm and
          pc-mm prefixed indices. (Exclude pc-mm-worker-report-log, pc-mm-list-subscriber-result-log
          and pc-mm-gf-imeicheck-log). Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(pc-mm-.*|pc-sm-app|pc-routing-app|vpn-gw-app)-log-.*$'
        - filtertype: pattern
          kind: regex
          value: '^pc-mm-(worker-report|list-subscriber-result|gf-imeicheck)-log.*$'
          exclude: True
        - filtertype: age
          source: field_stats
          direction: older
          field: '@timestamp'
          stats_result: max_value
          unit: days
          unit_count: 7
      2:
        action: delete_indices
        description: >-
          Delete indices older than 1000 days (based on index name), for isp log
          prefixed indices. Ignore the error if the filter does not result in
          an actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(pcc-isp-log).*$'
        - filtertype: age
          source: field_stats
          direction: older
          field: '@timestamp'
          stats_result: max_value
          unit: days
          unit_count: 1000
      3:
        action: delete_indices
        description: >-
          Delete indices older than 24 hours (based on index name), for indices
          that might contain sensitive information.
          Ignore the error if the filter does not result in an actionable list
          of indices(ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^pc-mm-(worker-report|list-subscriber-result|gf-imeicheck)-log.*$'
        - filtertype: age
          source: field_stats
          direction: older
          field: '@timestamp'
          stats_result: max_value
          unit: days
          unit_count: 1
      4:
        action: delete_indices
        description: >-
          Delete indices older than 30 days (based on index name), for audit log
          and alarm log prefixed indices. Ignore the error if the filter does
          not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(adp-app-audit-logs|adp-app-alarm-log).*$'
        - filtertype: age
          source: field_stats
          direction: older
          field: '@timestamp'
          stats_result: max_value
          unit: days
          unit_count: 30
      5:
        action: delete_indices
        description: >-
          Delete indices older than 7 days (based on index name), for common service.
          Ignore the error if the filter does not result in an actionable list of
          indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(adp-app-logs|pcc-kvdbrd-app-log).*$'
        - filtertype: age
          source: field_stats
          direction: older
          field: '@timestamp'
          stats_result: max_value
          unit: days
          unit_count: 7
      6:
        action: delete_indices
        description: >-
          Delete older indices when the total space is greater than upper limit, for pc-mm and
          pc-sm prefixed indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(pc-mm-.*|pc-sm-app)-log.*$'
        - filtertype: space
          disk_space: 25
          use_age: true
          source: creation_date
      7:
        action: delete_indices
        description: >-
          Delete older indices when the total space is greater than upper limit, for
          pc-routing-app-log prefixed indices. Ignore the error if the filter does not result
          in an actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(pc-routing-app-log).*$'
        - filtertype: space
          disk_space: 2
          use_age: true
          source: creation_date
      8:
        action: delete_indices
        description: >-
          Delete older indices when the total space is greater than upper limit, for isp log
          prefixed indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(pcc-isp-log).*$'
        - filtertype: space
          disk_space: 2
          use_age: true
          source: creation_date
      9:
        action: delete_indices
        description: >-
          Delete older indices when the total space is greater than upper limit, for audit log
          and alarm log prefixed indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(adp-app-audit-logs|adp-app-alarm-log).*$'
        - filtertype: space
          disk_space: 2
          use_age: true
          source: creation_date
      10:
        action: delete_indices
        description: >-
          Delete older indices when the total space is greater than upper limit, for isp log
          and vpn gw app log prefixed indices. Ignore the error if the filter does not result
          in an actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(vpn-gw-app-log).*$'
        - filtertype: space
          disk_space: 2
          use_age: true
          source: creation_date
      11:
        action: delete_indices
        description: >-
          Delete older indices when the total space is greater than upper limit, for common service
          prefixed indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(adp-app-logs|pcc-kvdbrd-app-log).*$'
        - filtertype: space
          disk_space: 28
          use_age: true
          source: creation_date


  eric-data-distributed-coordinator-ed:
    nodeSelector:
      dced:
        pcc-sm-pod: non-controller
    persistence:
      persistentVolumeClaim:
        size: "4Gi"

eric-cloud-native-nf-additions:

  eric-pm-bulk-reporter:
    # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
    resources:
      bulkreporter:
        requests:
          memory: 200Mi
    env:
      iscompressed: 'true'
      nodeName: n189-pcc

  eric-cm-yang-provider:
    # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
    resources:
      schemaSynchronizer:
        requests:
          memory: 128Mi
      sshd:
        requests:
          memory: 256Mi
      yangDbAdapter:
        requests:
          memory: 256Mi
    service:
      annotations:
        sharedVIPLabel: pcc1-oam
        addressPoolName: pcc1-oam

  eric-data-sftp-server:
    service:
      annotations:
        sharedVIPLabel: pcc1-oam
        addressPoolName: "pcc1-oam"
